import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, FileClock, RefreshCw, Search, ShieldCheck, UserRound, X } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Input } from "@/shared/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { listAuditLogs, type AuditLogRecord } from "../api";

const ACTION_OPTIONS = ["carrier.created","carrier.updated","carrier.deleted","broker.created","broker.updated","broker.deleted","load.created","load.updated","load.deleted","contact.created","contact.updated","contact.deleted","lead.created","lead.updated","lead.converted","lead.deleted","driver.created","driver.updated","driver.deleted","invoice.created","invoice.updated","invoice.payment.recorded","invoice.deleted","transaction.created","transaction.updated","transaction.deleted","company_profile.updated","document.created","document.updated","document.deleted","development.seed.completed"] as const;
const ENTITY_TYPES = [["carrier","Carrier"],["broker","Broker"],["load","Load"],["contact","Contact"],["lead","Lead"],["driver","Driver"],["invoice","Invoice"],["transaction","Transaction"],["company_profile","Company Profile"],["document","Document"],["development_dataset","Development Dataset"]] as const;
function formatDateTime(value: string) { return new Date(value).toLocaleString("en-US", { month:"short",day:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit" }); }
function ActionBadge({ action }: { action: string }) { const tone = action.endsWith(".deleted") ? "border-red-200 bg-red-50 text-red-700" : action.endsWith(".created") || action.endsWith(".completed") ? "border-emerald-200 bg-emerald-50 text-emerald-700" : action.endsWith(".converted") || action.includes("payment") ? "border-violet-200 bg-violet-50 text-violet-700" : "border-blue-200 bg-blue-50 text-blue-700"; return <span className={`inline-flex rounded-full border px-2 py-1 text-[10px] font-semibold ${tone}`}>{action.replaceAll(".", " ")}</span>; }
function Metadata({ entry }: { entry: AuditLogRecord }) { if (!entry.metadata || Object.keys(entry.metadata).length === 0) return null; return <details className="mt-3 rounded-lg border border-slate-200 bg-slate-50/50 p-3"><summary className="cursor-pointer text-xs font-medium text-slate-500">View metadata</summary><pre className="mt-3 max-h-56 overflow-auto rounded-lg bg-[#0B1E36] p-3 text-[11px] leading-5 text-slate-100">{JSON.stringify(entry.metadata, null, 2)}</pre></details>; }

export default function AuditLogPage() {
  const [search, setSearch] = useState("");
  const [action, setAction] = useState("all");
  const [entityType, setEntityType] = useState("all");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey:["audit-logs",search,action,entityType,page], queryFn:()=>listAuditLogs({ search:search||undefined, action:action==="all"?undefined:action, entityType:entityType==="all"?undefined:entityType, page, pageSize:100 }) });
  const source = query.data?.data ?? [];
  const entries = useMemo(() => source.filter((entry) => { const date = entry.createdAt.slice(0,10); if(startDate && date < startDate) return false; if(endDate && date > endDate) return false; return true; }), [source,startDate,endDate]);
  const meta=query.data?.meta;
  const hasFilters=Boolean(search||action!=="all"||entityType!=="all"||startDate||endDate);
  const clear=()=>{setSearch("");setAction("all");setEntityType("all");setStartDate("");setEndDate("");setPage(1)};
  const uniqueActors=new Set(entries.map((entry)=>entry.actorEmail).filter(Boolean)).size;
  const mutations=entries.filter((entry)=>!entry.action.includes("read")&&!entry.action.includes("view")).length;

  return <div className="flex flex-1 flex-col gap-5 overflow-y-auto p-4 sm:p-6 lg:p-8">
    <section className="grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Recorded Events</p><Activity className="h-4 w-4 text-[#1E3D7A]" /></div><p className="mt-2 text-2xl font-semibold">{meta?.total ?? 0}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Actors in View</p><UserRound className="h-4 w-4 text-[#1E3D7A]" /></div><p className="mt-2 text-2xl font-semibold">{uniqueActors}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Audit Mode</p><ShieldCheck className="h-4 w-4 text-[#1E3D7A]" /></div><p className="mt-2 text-sm font-semibold text-emerald-600">Read-only · {mutations} mutations in view</p></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-center"><Input type="date" className="w-full xl:w-40" aria-label="Audit start date" value={startDate} onChange={(e)=>{setStartDate(e.target.value);setPage(1)}}/><Input type="date" className="w-full xl:w-40" aria-label="Audit end date" value={endDate} onChange={(e)=>{setEndDate(e.target.value);setPage(1)}}/><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" placeholder="Search action, actor, ID or correlation..." value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1)}}/></div><Select value={entityType} onValueChange={(v)=>{setEntityType(v);setPage(1)}}><SelectTrigger className="w-full xl:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All entities</SelectItem>{ENTITY_TYPES.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={action} onValueChange={(v)=>{setAction(v);setPage(1)}}><SelectTrigger className="w-full xl:w-60"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All actions</SelectItem>{ACTION_OPTIONS.map((item)=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>void query.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>{hasFilters&&<Button variant="ghost" onClick={clear}><X className="mr-1 h-4 w-4"/>Clear</Button>}</div><div className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-500">{entries.length} events in the current view{meta ? ` · ${meta.total} total records` : ""}</div></section>
    {query.isError?<div className="rounded-xl border border-red-200 bg-white p-10 text-center"><p className="font-semibold">Audit events could not be loaded.</p><p className="mt-1 text-sm text-slate-500">{query.error instanceof Error?query.error.message:"Unknown API error."}</p><Button className="mt-4" variant="outline" onClick={()=>void query.refetch()}>Retry</Button></div>:query.isLoading?<div className="rounded-xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Loading audit history…</div>:entries.length===0?<div className="rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><FileClock className="mx-auto h-7 w-7 text-slate-300"/><p className="mt-3 font-semibold">No audit events found.</p><p className="mt-1 text-sm text-slate-500">Adjust the filters or wait for new audited operations.</p></div>:<div className="relative space-y-3 before:absolute before:bottom-3 before:left-[19px] before:top-3 before:w-px before:bg-slate-200">{entries.map((entry)=><article key={entry.id} className="relative ml-10 rounded-xl border border-slate-200 bg-white p-4"><span className="absolute -left-[30px] top-5 h-3 w-3 rounded-full border-2 border-white bg-[#1E3D7A] shadow"/><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><ActionBadge action={entry.action}/><span className="text-xs text-slate-400">{formatDateTime(entry.createdAt)}</span></div><p className="mt-3 text-sm font-semibold text-[#0B1E36]">{entry.summary}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span className="flex items-center gap-1.5"><UserRound className="h-3.5 w-3.5"/>{entry.actorEmail||"Local development user"}</span><span>{entry.entityType}{entry.entityId?` · ${entry.entityId}`:""}</span><span className="font-mono text-[10px]">event {entry.id}</span></div></div></div><Metadata entry={entry}/></article>)}</div>}
    {meta&&meta.totalPages>1?<div className="flex items-center justify-between"><p className="text-xs text-slate-500">Page {meta.page} of {meta.totalPages}</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>setPage((v)=>v-1)}>Previous</Button><Button variant="outline" size="sm" disabled={page>=meta.totalPages} onClick={()=>setPage((v)=>v+1)}>Next</Button></div></div>:null}
  </div>;
}
