import { execFileSync } from "node:child_process";
import process from "node:process";
import { assertDevSeedTarget } from "./dev-seed-guard";

function currentBranch(): string {
  if (process.env.GITHUB_REF_NAME) return process.env.GITHUB_REF_NAME;
  try {
    return execFileSync("git", ["branch", "--show-current"], {
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

function isoDate(offsetDays: number): string {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + offsetDays);
  return date.toISOString().slice(0, 10);
}

const target = assertDevSeedTarget({
  nodeEnv: process.env.NODE_ENV,
  appEnv: process.env.APP_ENV,
  confirmation: process.env.SEED_DEV_CONFIRM,
  branch: currentBranch(),
  databaseUrl: process.env.DATABASE_URL,
  allowedRemoteDatabase: process.env.SEED_DEV_ALLOWED_DATABASE,
});

const database = await import("@workspace/db");
const {
  auditLogsTable,
  brokersTable,
  carrierContactDetailsTable,
  carrierFleetDriverDetailsTable,
  carrierFleetTable,
  carriersTable,
  companyProfileTable,
  crmContactsTable,
  crmLeadsTable,
  db,
  driversTable,
  invoiceLoadsTable,
  invoicePaymentsTable,
  invoicesTable,
  loadVehiclesTable,
  loadsTable,
  pool,
  transactionsTable,
} = database;

const ids = {
  company: "d0000000-0000-4000-8000-000000000001",
  carriers: [
    "d1000000-0000-4000-8000-000000000001",
    "d1000000-0000-4000-8000-000000000002",
    "d1000000-0000-4000-8000-000000000003",
  ],
  carrierDetails: [
    "d1100000-0000-4000-8000-000000000001",
    "d1100000-0000-4000-8000-000000000002",
    "d1100000-0000-4000-8000-000000000003",
  ],
  fleet: [
    "d1200000-0000-4000-8000-000000000001",
    "d1200000-0000-4000-8000-000000000002",
    "d1200000-0000-4000-8000-000000000003",
  ],
  fleetDriverDetails: [
    "d1300000-0000-4000-8000-000000000001",
    "d1300000-0000-4000-8000-000000000002",
    "d1300000-0000-4000-8000-000000000003",
  ],
  brokers: [
    "d2000000-0000-4000-8000-000000000001",
    "d2000000-0000-4000-8000-000000000002",
    "d2000000-0000-4000-8000-000000000003",
  ],
  contacts: [
    "d3000000-0000-4000-8000-000000000001",
    "d3000000-0000-4000-8000-000000000002",
    "d3000000-0000-4000-8000-000000000003",
  ],
  leads: [
    "d4000000-0000-4000-8000-000000000001",
    "d4000000-0000-4000-8000-000000000002",
    "d4000000-0000-4000-8000-000000000003",
    "d4000000-0000-4000-8000-000000000004",
  ],
  drivers: [
    "d5000000-0000-4000-8000-000000000001",
    "d5000000-0000-4000-8000-000000000002",
    "d5000000-0000-4000-8000-000000000003",
  ],
  loads: [
    "d6000000-0000-4000-8000-000000000001",
    "d6000000-0000-4000-8000-000000000002",
    "d6000000-0000-4000-8000-000000000003",
    "d6000000-0000-4000-8000-000000000004",
    "d6000000-0000-4000-8000-000000000005",
    "d6000000-0000-4000-8000-000000000006",
    "d6000000-0000-4000-8000-000000000007",
    "d6000000-0000-4000-8000-000000000008",
  ],
  vehicles: [
    "d6100000-0000-4000-8000-000000000001",
    "d6100000-0000-4000-8000-000000000002",
    "d6100000-0000-4000-8000-000000000003",
    "d6100000-0000-4000-8000-000000000004",
    "d6100000-0000-4000-8000-000000000005",
    "d6100000-0000-4000-8000-000000000006",
    "d6100000-0000-4000-8000-000000000007",
    "d6100000-0000-4000-8000-000000000008",
    "d6100000-0000-4000-8000-000000000009",
  ],
  invoices: [
    "d7000000-0000-4000-8000-000000000001",
    "d7000000-0000-4000-8000-000000000002",
    "d7000000-0000-4000-8000-000000000003",
  ],
  invoiceLoads: [
    "d7100000-0000-4000-8000-000000000001",
    "d7100000-0000-4000-8000-000000000002",
    "d7100000-0000-4000-8000-000000000003",
    "d7100000-0000-4000-8000-000000000004",
    "d7100000-0000-4000-8000-000000000005",
  ],
  payments: [
    "d7200000-0000-4000-8000-000000000001",
    "d7200000-0000-4000-8000-000000000002",
  ],
  transactions: [
    "d8000000-0000-4000-8000-000000000001",
    "d8000000-0000-4000-8000-000000000002",
    "d8000000-0000-4000-8000-000000000003",
    "d8000000-0000-4000-8000-000000000004",
    "d8000000-0000-4000-8000-000000000005",
    "d8000000-0000-4000-8000-000000000006",
  ],
  audit: "d9000000-0000-4000-8000-000000000001",
} as const;

const companyProfile = {
  id: ids.company,
  companyName: "Lander Dispatch",
  legalCompanyName: "Lander Dispatch Services LLC",
  dbaName: "Lander Dispatch",
  einNumber: "88-1047296",
  mcNumber: "MC-1548207",
  usdotNumber: "USDOT-4027815",
  companyPhone: "+1 (407) 555-0140",
  companyEmail: "operations@landerdispatch.test",
  website: "https://landerdispatch.test",
  streetAddress: "6900 Tavistock Lakes Blvd",
  city: "Orlando",
  state: "FL",
  zipCode: "32827",
  country: "USA",
  businessHours: "Mon–Fri 8:00 AM–6:00 PM ET",
  updatedAt: new Date(),
};

const carriers = [
  {
    id: ids.carriers[0],
    companyName: "Atlantic Auto Transport LLC",
    carrierType: "Owner Operator",
    website: "https://atlantic-auto.test",
    usdotNumber: "USDOT-3178421",
    mcNumber: "MC-1045827",
    einNumber: "59-8742103",
    status: "Active",
    priority: "High",
    rating: "4.9",
    tags: ["Preferred", "Enclosed capable", "Southeast"],
    notes: "Reliable owner operator for premium and enclosed vehicle moves.",
    primaryContact: "Marcus Reed",
    phone: "+1 (904) 555-0101",
    email: "dispatch@atlantic-auto.test",
    lastContact: isoDate(-1),
    companyAddress: "1840 Portside Drive",
    companyCity: "Jacksonville",
    companyState: "FL",
    companyZip: "32226",
    operatingStates: ["FL", "GA", "SC", "NC", "AL"],
    serviceTypes: ["Open Transport", "Enclosed Transport"],
    ratePerMile: "1.9500",
    insuranceExpiration: isoDate(210),
    authorityStatus: "Active",
    paymentTerms: "Net 7",
    quickPay: true,
    factoringCompany: "Triumph Business Capital",
    factoringFee: "2.5000",
    bankName: "Development Bank",
    accountHolder: "Atlantic Auto Transport LLC",
    accountNumberLast4: "4821",
    routingNumberLast4: "0098",
    bankAddress: "100 Test Banking Way",
    bankCity: "Jacksonville",
    bankState: "FL",
    bankZip: "32202",
    zelleAccount: "billing@atlantic-auto.test",
    cashAppAccount: "$AtlanticAutoTest",
    lastLoadDate: isoDate(-2),
    updatedAt: new Date(),
  },
  {
    id: ids.carriers[1],
    companyName: "Blue Ridge Vehicle Logistics",
    carrierType: "Fleet",
    website: "https://blueridge-logistics.test",
    usdotNumber: "USDOT-2984107",
    mcNumber: "MC-982145",
    einNumber: "56-7319024",
    status: "Active",
    priority: "Medium",
    rating: "4.7",
    tags: ["Fleet", "Mid-Atlantic", "Auction"],
    notes: "Three-truck fleet with strong auction pickup performance.",
    primaryContact: "Elena Torres",
    phone: "+1 (704) 555-0112",
    email: "loads@blueridge-logistics.test",
    lastContact: isoDate(-3),
    companyAddress: "4200 Logistics Parkway",
    companyCity: "Charlotte",
    companyState: "NC",
    companyZip: "28208",
    operatingStates: ["NC", "SC", "VA", "TN", "GA"],
    serviceTypes: ["Open Transport", "Dealer Transfers"],
    ratePerMile: "1.7800",
    insuranceExpiration: isoDate(145),
    authorityStatus: "Active",
    paymentTerms: "Net 15",
    quickPay: false,
    factoringCompany: "OTR Solutions",
    factoringFee: "2.7500",
    bankName: "Development Bank",
    accountHolder: "Blue Ridge Vehicle Logistics",
    accountNumberLast4: "7734",
    routingNumberLast4: "1021",
    lastLoadDate: isoDate(-4),
    updatedAt: new Date(),
  },
  {
    id: ids.carriers[2],
    companyName: "Sunline Hauling Group",
    carrierType: "Fleet",
    website: "https://sunline-hauling.test",
    usdotNumber: "USDOT-4017682",
    mcNumber: "MC-1529074",
    einNumber: "74-5102948",
    status: "Pending",
    priority: "Low",
    rating: "4.3",
    tags: ["Texas", "Onboarding"],
    notes: "Authority active; insurance certificate review still pending.",
    primaryContact: "Caleb Brooks",
    phone: "+1 (214) 555-0130",
    email: "operations@sunline-hauling.test",
    lastContact: isoDate(-5),
    companyAddress: "8100 Trinity Boulevard",
    companyCity: "Fort Worth",
    companyState: "TX",
    companyZip: "76118",
    operatingStates: ["TX", "OK", "LA", "NM"],
    serviceTypes: ["Open Transport"],
    ratePerMile: "1.7200",
    insuranceExpiration: isoDate(78),
    authorityStatus: "Active — Insurance Review",
    paymentTerms: "Net 15",
    quickPay: true,
    factoringCompany: null,
    factoringFee: null,
    lastLoadDate: isoDate(-10),
    updatedAt: new Date(),
  },
];

const carrierDetails = [
  {
    id: ids.carrierDetails[0],
    carrierId: ids.carriers[0],
    phone2: "+1 (904) 555-0102",
    emergencyContactName: "Dana Reed",
    emergencyPhone: "+1 (904) 555-0199",
    emergencyPhone2: "+1 (904) 555-0188",
    weeklyMinimumAmount: "6500.00",
    totalTripsPerWeek: 5,
    updatedAt: new Date(),
  },
  {
    id: ids.carrierDetails[1],
    carrierId: ids.carriers[1],
    phone2: "+1 (704) 555-0113",
    emergencyContactName: "Blue Ridge Night Dispatch",
    emergencyPhone: "+1 (704) 555-0190",
    emergencyPhone2: "+1 (704) 555-0191",
    weeklyMinimumAmount: "12000.00",
    totalTripsPerWeek: 10,
    updatedAt: new Date(),
  },
  {
    id: ids.carrierDetails[2],
    carrierId: ids.carriers[2],
    phone2: "+1 (214) 555-0131",
    emergencyContactName: "Sunline After Hours",
    emergencyPhone: "+1 (214) 555-0192",
    emergencyPhone2: null,
    weeklyMinimumAmount: "9000.00",
    totalTripsPerWeek: 7,
    updatedAt: new Date(),
  },
];

const fleet = [
  {
    id: ids.fleet[0],
    carrierId: ids.carriers[0],
    sortOrder: 0,
    truckYear: "2022",
    truckMake: "Ram",
    truckModel: "3500 Limited",
    truckVin: "3C63RRGL7NG100101",
    truckColor: "Black",
    truckPlateNumber: "FL-DV101",
    trailerYear: "2023",
    trailerMake: "Kaufman",
    trailerModel: "EZ-4 Car Hauler",
    trailerVin: "5VGFE4823PC100101",
    trailerColor: "Black",
    trailerPlateNumber: "FL-TR101",
    driverName: "Marcus Reed",
    driverPhone: "+1 (904) 555-0101",
    driverEmail: "marcus@atlantic-auto.test",
  },
  {
    id: ids.fleet[1],
    carrierId: ids.carriers[1],
    sortOrder: 0,
    truckYear: "2021",
    truckMake: "Peterbilt",
    truckModel: "389",
    truckVin: "1XPHDP9X1MN100202",
    truckColor: "Blue",
    truckPlateNumber: "NC-DV202",
    trailerYear: "2022",
    trailerMake: "Cottrell",
    trailerModel: "CX-09LS",
    trailerVin: "5E0AA1442NG100202",
    trailerColor: "Silver",
    trailerPlateNumber: "NC-TR202",
    driverName: "Elena Torres",
    driverPhone: "+1 (704) 555-0112",
    driverEmail: "elena@blueridge-logistics.test",
  },
  {
    id: ids.fleet[2],
    carrierId: ids.carriers[2],
    sortOrder: 0,
    truckYear: "2020",
    truckMake: "Ford",
    truckModel: "F-450 Platinum",
    truckVin: "1FDUF4HT7LEC00303",
    truckColor: "White",
    truckPlateNumber: "TX-DV303",
    trailerYear: "2021",
    trailerMake: "Take 3",
    trailerModel: "53-Foot Wedge",
    trailerVin: "1T9FS5337MB100303",
    trailerColor: "White",
    trailerPlateNumber: "TX-TR303",
    driverName: "Caleb Brooks",
    driverPhone: "+1 (214) 555-0130",
    driverEmail: "caleb@sunline-hauling.test",
  },
];

const fleetDriverDetails = [
  {
    id: ids.fleetDriverDetails[0],
    fleetId: ids.fleet[0],
    phone2: "+1 (904) 555-0102",
    emergencyContactName: "Dana Reed",
    emergencyPhone: "+1 (904) 555-0199",
    emergencyPhone2: null,
    licenseType: "CDL Class A",
    cdlNumber: "FL-CDL-9100101",
    twicCard: true,
    updatedAt: new Date(),
  },
  {
    id: ids.fleetDriverDetails[1],
    fleetId: ids.fleet[1],
    phone2: "+1 (704) 555-0114",
    emergencyContactName: "Luis Torres",
    emergencyPhone: "+1 (704) 555-0180",
    emergencyPhone2: null,
    licenseType: "CDL Class A",
    cdlNumber: "NC-CDL-8200202",
    twicCard: true,
    updatedAt: new Date(),
  },
  {
    id: ids.fleetDriverDetails[2],
    fleetId: ids.fleet[2],
    phone2: null,
    emergencyContactName: "Megan Brooks",
    emergencyPhone: "+1 (214) 555-0183",
    emergencyPhone2: null,
    licenseType: "CDL Class A",
    cdlNumber: "TX-CDL-7300303",
    twicCard: false,
    updatedAt: new Date(),
  },
];

const brokers = [
  {
    id: ids.brokers[0],
    companyName: "Meridian Auto Freight",
    brokerType: "Freight Broker",
    website: "https://meridian-auto.test",
    mcNumber: "MC-812340",
    usdotNumber: "USDOT-2481063",
    primaryContact: "Olivia Bennett",
    phone: "+1 (305) 555-0201",
    email: "loads@meridian-auto.test",
    lastContact: isoDate(-1),
    freightTypes: ["Auto Transport", "Dealer Transfers"],
    coverage: "Nationwide",
    selectedStates: ["FL", "GA", "NC", "SC", "TX", "CA"],
    paymentTerms: "Net 15",
    paymentDays: 14,
    quickPay: true,
    quickPayFee: "2.0000",
    factoringAccepted: "Yes",
    onboardingStatus: "Completed",
    rating: "4.8",
    status: "Active",
    priority: "High",
    tags: ["Preferred", "High volume"],
    notes: "Primary source for dealer and auction vehicle volume.",
    updatedAt: new Date(),
  },
  {
    id: ids.brokers[1],
    companyName: "Apex Dealer Logistics",
    brokerType: "3PL",
    website: "https://apex-dealer.test",
    mcNumber: "MC-934501",
    usdotNumber: "USDOT-3014528",
    primaryContact: "Nathan Cole",
    phone: "+1 (615) 555-0202",
    email: "dispatch@apex-dealer.test",
    lastContact: isoDate(-4),
    freightTypes: ["Auto Transport"],
    coverage: "Southeast and Midwest",
    selectedStates: ["TN", "KY", "OH", "IN", "GA", "FL"],
    paymentTerms: "Net 30",
    paymentDays: 28,
    quickPay: true,
    quickPayFee: "3.0000",
    factoringAccepted: "Yes",
    onboardingStatus: "Completed",
    rating: "4.5",
    status: "Active",
    priority: "Medium",
    tags: ["Dealer network"],
    notes: "Consistent dealer transfer work with moderate seasonal peaks.",
    updatedAt: new Date(),
  },
  {
    id: ids.brokers[2],
    companyName: "Horizon Auction Transport",
    brokerType: "Freight Broker",
    website: "https://horizon-auction.test",
    mcNumber: "MC-1102874",
    usdotNumber: "USDOT-3521109",
    primaryContact: "Sophia Nguyen",
    phone: "+1 (713) 555-0203",
    email: "carrier@horizon-auction.test",
    lastContact: isoDate(-7),
    freightTypes: ["Auto Transport", "Auction"],
    coverage: "Texas and Gulf Coast",
    selectedStates: ["TX", "LA", "OK", "AR"],
    paymentTerms: "Net 15",
    paymentDays: 17,
    quickPay: false,
    quickPayFee: null,
    factoringAccepted: "Yes",
    onboardingStatus: "In Progress",
    rating: "4.2",
    status: "Pending",
    priority: "Low",
    tags: ["Auction", "Gulf Coast"],
    notes: "Carrier packet is under final review.",
    updatedAt: new Date(),
  },
];

const contacts = [
  {
    id: ids.contacts[0],
    companyName: "Southeast Auto Auction",
    contactType: "Auction",
    status: "Active",
    priority: "High",
    rating: "4.8",
    primaryContactName: "Grace Palmer",
    primaryPhoneNumber: "+1 (407) 555-0301",
    primaryPhoneNumber2: "+1 (407) 555-0302",
    email: "logistics@southeast-auction.test",
    website: "https://southeast-auction.test",
    emergencyContactName: "Auction Security Desk",
    emergencyPhoneNumber: "+1 (407) 555-0399",
    streetAddress: "1200 Auction Lane",
    city: "Sanford",
    state: "FL",
    zipCode: "32771",
    coverageArea: "Florida and Southeast",
    businessHours: "Mon–Sat 7:00 AM–7:00 PM",
    emergencyService: true,
    services: "Auction releases, vehicle storage and gate coordination",
    lastContact: isoDate(-2),
    tags: ["Auction", "High volume"],
    notes: "Requires gate pass confirmation before every pickup.",
    updatedAt: new Date(),
  },
  {
    id: ids.contacts[1],
    companyName: "Palmetto Motors Group",
    contactType: "Dealer",
    status: "Active",
    priority: "Medium",
    rating: "4.6",
    primaryContactName: "Eric Dawson",
    primaryPhoneNumber: "+1 (803) 555-0303",
    email: "inventory@palmetto-motors.test",
    website: "https://palmetto-motors.test",
    streetAddress: "4550 Dealer Row",
    city: "Columbia",
    state: "SC",
    zipCode: "29209",
    coverageArea: "Carolinas",
    businessHours: "Mon–Fri 8:00 AM–6:00 PM",
    emergencyService: false,
    services: "Dealer transfers and wholesale inventory movement",
    lastContact: isoDate(-6),
    tags: ["Dealer", "Recurring"],
    notes: "Weekly transfer list is released every Monday morning.",
    updatedAt: new Date(),
  },
  {
    id: ids.contacts[2],
    companyName: "Coastal Fleet Rentals",
    contactType: "Fleet / Rental Company",
    status: "Active",
    priority: "Medium",
    rating: "4.4",
    primaryContactName: "Maya Collins",
    primaryPhoneNumber: "+1 (843) 555-0304",
    email: "fleetops@coastal-rentals.test",
    website: "https://coastal-rentals.test",
    streetAddress: "900 Fleet Center Drive",
    city: "Charleston",
    state: "SC",
    zipCode: "29407",
    coverageArea: "Southeast coastal markets",
    businessHours: "Daily 6:00 AM–10:00 PM",
    emergencyService: true,
    services: "Fleet repositioning and seasonal vehicle balancing",
    lastContact: isoDate(-3),
    tags: ["Fleet", "Seasonal"],
    notes: "Peak demand occurs before holiday travel periods.",
    updatedAt: new Date(),
  },
];

const leads = [
  {
    id: ids.leads[0],
    companyName: "Granite Motors Network",
    leadType: "Dealer",
    primaryContact: "Aaron Price",
    phone: "+1 (603) 555-0401",
    email: "aaron@granite-motors.test",
    website: "https://granite-motors.test",
    streetAddress: "80 Commerce Avenue",
    city: "Manchester",
    state: "NH",
    zipCode: "03101",
    serviceTypes: ["Dealer Transfers", "Open Transport"],
    operatingStates: ["NH", "MA", "ME", "VT", "NY"],
    estimatedWeeklyLoads: 8,
    estimatedWeeklyRevenue: "11800.00",
    leadSource: "Outbound Prospecting",
    pipelineStage: "Qualified",
    priority: "High",
    rating: "4.5",
    status: "Active",
    nextFollowUpDate: isoDate(2),
    nextFollowUpTime: "10:30",
    followUpNotes: "Review the proposed Northeast lane pricing.",
    lastContact: isoDate(-2),
    tags: ["Dealer", "Northeast"],
    notes: "Five-store dealer group evaluating centralized dispatch.",
    updatedAt: new Date(),
  },
  {
    id: ids.leads[1],
    companyName: "Eastline Auctions",
    leadType: "Auction",
    primaryContact: "Rebecca Stone",
    phone: "+1 (804) 555-0402",
    email: "rebecca@eastline-auctions.test",
    website: "https://eastline-auctions.test",
    city: "Richmond",
    state: "VA",
    zipCode: "23224",
    serviceTypes: ["Auction Pickup", "Vehicle Storage Transfer"],
    operatingStates: ["VA", "MD", "DC", "NC"],
    estimatedWeeklyLoads: 14,
    estimatedWeeklyRevenue: "19600.00",
    leadSource: "Referral",
    pipelineStage: "Proposal Sent",
    priority: "High",
    rating: "4.7",
    status: "Active",
    nextFollowUpDate: isoDate(1),
    nextFollowUpTime: "14:00",
    followUpNotes: "Confirm gate release API and billing requirements.",
    lastContact: isoDate(-1),
    tags: ["Auction", "High volume"],
    notes: "Large weekly auction with a need for overflow capacity.",
    updatedAt: new Date(),
  },
  {
    id: ids.leads[2],
    companyName: "Metro Rental Fleet",
    leadType: "Fleet / Rental Company",
    primaryContact: "Jordan Ellis",
    phone: "+1 (404) 555-0403",
    email: "jordan@metro-rental.test",
    website: "https://metro-rental.test",
    city: "Atlanta",
    state: "GA",
    zipCode: "30337",
    serviceTypes: ["Fleet Repositioning"],
    operatingStates: ["GA", "FL", "TN", "NC", "SC"],
    estimatedWeeklyLoads: 10,
    estimatedWeeklyRevenue: "14250.00",
    leadSource: "Website Inquiry",
    pipelineStage: "Contacted",
    priority: "Medium",
    rating: "4.1",
    status: "Active",
    nextFollowUpDate: isoDate(4),
    nextFollowUpTime: "09:00",
    followUpNotes: "Collect seasonal lane forecast and insurance requirements.",
    lastContact: isoDate(-3),
    tags: ["Fleet", "Southeast"],
    notes: "Interested in seasonal relocation support.",
    updatedAt: new Date(),
  },
  {
    id: ids.leads[3],
    companyName: "Nova Manufacturing Mobility",
    leadType: "Manufacturer",
    primaryContact: "Priya Shah",
    phone: "+1 (512) 555-0404",
    email: "priya@nova-mobility.test",
    website: "https://nova-mobility.test",
    city: "Austin",
    state: "TX",
    zipCode: "78744",
    serviceTypes: ["Prototype Transport", "Enclosed Transport"],
    operatingStates: ["TX", "CA", "AZ", "NV"],
    estimatedWeeklyLoads: 3,
    estimatedWeeklyRevenue: "9600.00",
    leadSource: "Industry Event",
    pipelineStage: "New Lead",
    priority: "Medium",
    rating: "4.0",
    status: "Active",
    nextFollowUpDate: isoDate(7),
    nextFollowUpTime: "15:30",
    followUpNotes: "Schedule security and enclosed-equipment discovery call.",
    lastContact: isoDate(-5),
    tags: ["Manufacturer", "Prototype"],
    notes: "Requires enclosed transport and strict delivery confidentiality.",
    updatedAt: new Date(),
  },
];

const drivers = [
  {
    id: ids.drivers[0],
    fullName: "Marcus Reed",
    status: "Active",
    dateOfBirth: "1988-06-14",
    phoneNumber: "+1 (904) 555-0101",
    phoneNumber2: "+1 (904) 555-0102",
    email: "marcus@atlantic-auto.test",
    emergencyContactName: "Dana Reed",
    emergencyPhoneNumber: "+1 (904) 555-0199",
    streetAddress: "1840 Portside Drive",
    city: "Jacksonville",
    state: "FL",
    zipCode: "32226",
    hireDate: isoDate(-720),
    driverType: "Company Driver",
    employmentType: "Full Time",
    yearsOfExperience: 9,
    assignedEquipmentId: ids.fleet[0],
    driverLicenseNumber: "FL-R300-540-88-214-0",
    driverLicenseState: "FL",
    driverLicenseClass: "E",
    driverLicenseExpiration: isoDate(520),
    cdlNumber: "FL-CDL-9100101",
    cdlState: "FL",
    cdlClass: "A",
    cdlExpiration: isoDate(410),
    cdlEndorsements: ["T"],
    cdlRestrictions: "None",
    hazmatEndorsement: false,
    medicalExaminerCertificateNumber: "MED-FL-100101",
    medicalCardIssueDate: isoDate(-120),
    medicalCardExpiration: isoDate(610),
    medicalExaminerName: "Dr. Amelia Grant",
    nationalRegistryNumber: "NR-1748201",
    twicCardNumber: "TWIC-100101",
    twicCardExpiration: isoDate(840),
    driverQualificationFileStatus: "Complete",
    mvrCheckDate: isoDate(-30),
    mvrNextReviewDate: isoDate(335),
    mvrStatus: "Clear",
    backgroundCheckDate: isoDate(-300),
    backgroundCheckStatus: "Clear",
    drugTestDate: isoDate(-90),
    drugTestResult: "Negative",
    alcoholTestDate: isoDate(-90),
    alcoholTestResult: "Negative",
    clearinghouseStatus: "Clear",
    clearinghouseLastQueryDate: isoDate(-40),
    clearinghouseNextQueryDate: isoDate(325),
    complianceStatus: "Compliant",
    accidentHistory: "No preventable accidents reported.",
    violationHistory: "No moving violations in the last 36 months.",
    assignedCarrierId: ids.carriers[0],
    assignedTruckId: ids.fleet[0],
    assignedTrailerId: ids.fleet[0],
    lastLoad: isoDate(-2),
    totalLoads: 186,
    lastAssignmentDate: isoDate(-2),
    notes: "Preferred driver for premium and enclosed vehicle movements.",
    tags: ["Enclosed", "TWIC", "Preferred"],
    updatedAt: new Date(),
  },
  {
    id: ids.drivers[1],
    fullName: "Elena Torres",
    status: "Active",
    dateOfBirth: "1991-11-03",
    phoneNumber: "+1 (704) 555-0112",
    phoneNumber2: "+1 (704) 555-0114",
    email: "elena@blueridge-logistics.test",
    emergencyContactName: "Luis Torres",
    emergencyPhoneNumber: "+1 (704) 555-0180",
    streetAddress: "4200 Logistics Parkway",
    city: "Charlotte",
    state: "NC",
    zipCode: "28208",
    hireDate: isoDate(-540),
    driverType: "Company Driver",
    employmentType: "Full Time",
    yearsOfExperience: 7,
    assignedEquipmentId: ids.fleet[1],
    driverLicenseNumber: "NC-6134829",
    driverLicenseState: "NC",
    driverLicenseClass: "C",
    driverLicenseExpiration: isoDate(470),
    cdlNumber: "NC-CDL-8200202",
    cdlState: "NC",
    cdlClass: "A",
    cdlExpiration: isoDate(365),
    cdlEndorsements: ["T"],
    cdlRestrictions: "Corrective lenses",
    hazmatEndorsement: false,
    medicalExaminerCertificateNumber: "MED-NC-200202",
    medicalCardIssueDate: isoDate(-80),
    medicalCardExpiration: isoDate(650),
    medicalExaminerName: "Dr. Nathan Fields",
    nationalRegistryNumber: "NR-2849302",
    twicCardNumber: "TWIC-200202",
    twicCardExpiration: isoDate(760),
    driverQualificationFileStatus: "Complete",
    mvrCheckDate: isoDate(-42),
    mvrNextReviewDate: isoDate(323),
    mvrStatus: "Clear",
    backgroundCheckDate: isoDate(-250),
    backgroundCheckStatus: "Clear",
    drugTestDate: isoDate(-65),
    drugTestResult: "Negative",
    alcoholTestDate: isoDate(-65),
    alcoholTestResult: "Negative",
    clearinghouseStatus: "Clear",
    clearinghouseLastQueryDate: isoDate(-35),
    clearinghouseNextQueryDate: isoDate(330),
    complianceStatus: "Compliant",
    assignedCarrierId: ids.carriers[1],
    assignedTruckId: ids.fleet[1],
    assignedTrailerId: ids.fleet[1],
    lastLoad: isoDate(-4),
    totalLoads: 142,
    lastAssignmentDate: isoDate(-4),
    notes: "Strong auction pickup and multi-stop route performance.",
    tags: ["Auction", "TWIC"],
    updatedAt: new Date(),
  },
  {
    id: ids.drivers[2],
    fullName: "Caleb Brooks",
    status: "Pending",
    dateOfBirth: "1986-02-21",
    phoneNumber: "+1 (214) 555-0130",
    email: "caleb@sunline-hauling.test",
    emergencyContactName: "Megan Brooks",
    emergencyPhoneNumber: "+1 (214) 555-0183",
    streetAddress: "8100 Trinity Boulevard",
    city: "Fort Worth",
    state: "TX",
    zipCode: "76118",
    hireDate: isoDate(-180),
    driverType: "Owner Operator",
    employmentType: "Contractor",
    yearsOfExperience: 11,
    assignedEquipmentId: ids.fleet[2],
    driverLicenseNumber: "TX-29841073",
    driverLicenseState: "TX",
    driverLicenseClass: "C",
    driverLicenseExpiration: isoDate(390),
    cdlNumber: "TX-CDL-7300303",
    cdlState: "TX",
    cdlClass: "A",
    cdlExpiration: isoDate(280),
    cdlEndorsements: ["T"],
    cdlRestrictions: "None",
    hazmatEndorsement: false,
    medicalExaminerCertificateNumber: "MED-TX-300303",
    medicalCardIssueDate: isoDate(-140),
    medicalCardExpiration: isoDate(590),
    medicalExaminerName: "Dr. Rachel Owens",
    nationalRegistryNumber: "NR-3950403",
    twicCardNumber: null,
    twicCardExpiration: null,
    driverQualificationFileStatus: "Documents Pending",
    mvrCheckDate: isoDate(-20),
    mvrNextReviewDate: isoDate(345),
    mvrStatus: "Clear",
    backgroundCheckDate: isoDate(-150),
    backgroundCheckStatus: "Clear",
    drugTestDate: isoDate(-45),
    drugTestResult: "Negative",
    alcoholTestDate: isoDate(-45),
    alcoholTestResult: "Negative",
    clearinghouseStatus: "Clear",
    clearinghouseLastQueryDate: isoDate(-25),
    clearinghouseNextQueryDate: isoDate(340),
    complianceStatus: "Review Required",
    assignedCarrierId: ids.carriers[2],
    assignedTruckId: ids.fleet[2],
    assignedTrailerId: ids.fleet[2],
    lastLoad: isoDate(-10),
    totalLoads: 98,
    lastAssignmentDate: isoDate(-10),
    notes: "TWIC verification and final insurance packet are pending.",
    tags: ["Texas", "Onboarding"],
    updatedAt: new Date(),
  },
];

const loads = [
  {
    id: ids.loads[0],
    loadId: "LD-DEV-1001",
    carrierId: ids.carriers[0],
    brokerId: ids.brokers[0],
    status: "Delivered",
    dispatchDate: isoDate(-12),
    pickupName: "Southeast Auto Auction",
    pickupAddress: "1200 Auction Lane",
    pickupCity: "Sanford",
    pickupState: "FL",
    pickupZip: "32771",
    pickupPhone: "+1 (407) 555-0301",
    pickupContactName: "Grace Palmer",
    pickupEstimated: isoDate(-11),
    pickupDeadline: isoDate(-10),
    deliveryName: "Palmetto Motors Group",
    deliveryAddress: "4550 Dealer Row",
    deliveryCity: "Columbia",
    deliveryState: "SC",
    deliveryZip: "29209",
    deliveryPhone: "+1 (803) 555-0303",
    deliveryContactName: "Eric Dawson",
    deliveryEstimated: isoDate(-9),
    deliveryDeadline: isoDate(-8),
    miles: "420.00",
    rate: "1250.00",
    carrierPay: "1050.00",
    fuelSurcharge: "75.00",
    ratePerMile: "2.9762",
    freightType: "Auto Transport",
    equipmentType: "Open 4-Car",
    weight: "4300.00",
    paymentMethod: "ACH",
    paymentStatus: "Paid",
    dispatchInstructions: "Confirm auction release before arrival.",
    pickupInstructions: "Use north commercial gate.",
    deliveryInstructions: "Check in with wholesale inventory office.",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[1],
    loadId: "LD-DEV-1002",
    carrierId: ids.carriers[0],
    brokerId: ids.brokers[0],
    status: "Delivered",
    dispatchDate: isoDate(-9),
    pickupName: "Luxury Imports Miami",
    pickupAddress: "7900 NW 25th Street",
    pickupCity: "Miami",
    pickupState: "FL",
    pickupZip: "33122",
    pickupContactName: "Receiving Desk",
    pickupEstimated: isoDate(-8),
    deliveryName: "Prestige Motors Atlanta",
    deliveryAddress: "3500 Peachtree Road",
    deliveryCity: "Atlanta",
    deliveryState: "GA",
    deliveryZip: "30326",
    deliveryContactName: "James Wilcox",
    deliveryEstimated: isoDate(-6),
    miles: "665.00",
    rate: "1850.00",
    carrierPay: "1570.00",
    fuelSurcharge: "110.00",
    ratePerMile: "2.7820",
    freightType: "Auto Transport",
    equipmentType: "Enclosed",
    weight: "4100.00",
    paymentMethod: "ACH",
    paymentStatus: "Paid",
    dispatchInstructions: "Premium vehicle — enclosed transport required.",
    pickupInstructions: "Photograph all four sides before loading.",
    deliveryInstructions: "Call 60 minutes before arrival.",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[2],
    loadId: "LD-DEV-1003",
    carrierId: ids.carriers[1],
    brokerId: ids.brokers[1],
    status: "Delivered",
    dispatchDate: isoDate(-8),
    pickupName: "Nashville Dealer Exchange",
    pickupAddress: "2500 Murfreesboro Pike",
    pickupCity: "Nashville",
    pickupState: "TN",
    pickupZip: "37217",
    deliveryName: "Queen City Auto Mall",
    deliveryAddress: "4100 Independence Boulevard",
    deliveryCity: "Charlotte",
    deliveryState: "NC",
    deliveryZip: "28205",
    pickupEstimated: isoDate(-7),
    deliveryEstimated: isoDate(-5),
    miles: "410.00",
    rate: "1100.00",
    carrierPay: "930.00",
    fuelSurcharge: "65.00",
    ratePerMile: "2.6829",
    freightType: "Auto Transport",
    equipmentType: "Open 9-Car",
    weight: "3900.00",
    paymentMethod: "ACH",
    paymentStatus: "Paid",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[3],
    loadId: "LD-DEV-1004",
    carrierId: ids.carriers[1],
    brokerId: ids.brokers[0],
    status: "In Route",
    dispatchDate: isoDate(-2),
    pickupName: "Raleigh Fleet Center",
    pickupAddress: "5500 Capital Boulevard",
    pickupCity: "Raleigh",
    pickupState: "NC",
    pickupZip: "27616",
    deliveryName: "Coastal Fleet Rentals",
    deliveryAddress: "900 Fleet Center Drive",
    deliveryCity: "Charleston",
    deliveryState: "SC",
    deliveryZip: "29407",
    pickupEstimated: isoDate(-1),
    deliveryEstimated: isoDate(1),
    miles: "280.00",
    rate: "980.00",
    carrierPay: "820.00",
    fuelSurcharge: "55.00",
    ratePerMile: "3.5000",
    freightType: "Fleet Repositioning",
    equipmentType: "Open 9-Car",
    weight: "3600.00",
    paymentMethod: "ACH",
    paymentStatus: "Pending",
    dispatchInstructions: "Multi-unit fleet relocation.",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[4],
    loadId: "LD-DEV-1005",
    carrierId: ids.carriers[0],
    brokerId: ids.brokers[1],
    status: "Picked Up",
    dispatchDate: isoDate(-1),
    pickupName: "Orlando Dealer Hub",
    pickupAddress: "6200 South Orange Blossom Trail",
    pickupCity: "Orlando",
    pickupState: "FL",
    pickupZip: "32809",
    deliveryName: "Savannah Luxury Auto",
    deliveryAddress: "100 Motor Row",
    deliveryCity: "Savannah",
    deliveryState: "GA",
    deliveryZip: "31405",
    pickupEstimated: isoDate(0),
    deliveryEstimated: isoDate(2),
    miles: "285.00",
    rate: "1050.00",
    carrierPay: "880.00",
    fuelSurcharge: "60.00",
    ratePerMile: "3.6842",
    freightType: "Auto Transport",
    equipmentType: "Enclosed",
    weight: "4500.00",
    paymentMethod: "ACH",
    paymentStatus: "Pending",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[5],
    loadId: "LD-DEV-1006",
    carrierId: ids.carriers[2],
    brokerId: ids.brokers[2],
    status: "Dispatched",
    dispatchDate: isoDate(0),
    pickupName: "Dallas Auction Center",
    pickupAddress: "1500 Auction Road",
    pickupCity: "Dallas",
    pickupState: "TX",
    pickupZip: "75247",
    deliveryName: "Houston Dealer Group",
    deliveryAddress: "7200 Gulf Freeway",
    deliveryCity: "Houston",
    deliveryState: "TX",
    deliveryZip: "77017",
    pickupEstimated: isoDate(1),
    deliveryEstimated: isoDate(3),
    miles: "245.00",
    rate: "875.00",
    carrierPay: "735.00",
    fuelSurcharge: "45.00",
    ratePerMile: "3.5714",
    freightType: "Auction",
    equipmentType: "Open 3-Car",
    weight: "4000.00",
    paymentMethod: "ACH",
    paymentStatus: "Pending",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[6],
    loadId: "LD-DEV-1007",
    carrierId: ids.carriers[1],
    brokerId: ids.brokers[1],
    status: "New",
    dispatchDate: isoDate(2),
    pickupName: "Columbus Dealer Exchange",
    pickupAddress: "8800 Alum Creek Drive",
    pickupCity: "Columbus",
    pickupState: "OH",
    pickupZip: "43207",
    deliveryName: "Charlotte Auto Collection",
    deliveryAddress: "9700 South Boulevard",
    deliveryCity: "Charlotte",
    deliveryState: "NC",
    deliveryZip: "28273",
    pickupEstimated: isoDate(3),
    deliveryEstimated: isoDate(5),
    miles: "430.00",
    rate: "1325.00",
    carrierPay: "1120.00",
    fuelSurcharge: "70.00",
    ratePerMile: "3.0814",
    freightType: "Dealer Transfer",
    equipmentType: "Open 9-Car",
    weight: "3950.00",
    paymentMethod: "ACH",
    paymentStatus: "Pending",
    updatedAt: new Date(),
  },
  {
    id: ids.loads[7],
    loadId: "LD-DEV-1008",
    carrierId: ids.carriers[0],
    brokerId: ids.brokers[0],
    status: "Canceled",
    dispatchDate: isoDate(-5),
    pickupName: "Tampa Wholesale Auto",
    pickupAddress: "4200 Adamo Drive",
    pickupCity: "Tampa",
    pickupState: "FL",
    pickupZip: "33605",
    deliveryName: "Birmingham Motor Group",
    deliveryAddress: "1900 Automotive Avenue",
    deliveryCity: "Birmingham",
    deliveryState: "AL",
    deliveryZip: "35210",
    pickupEstimated: isoDate(-4),
    deliveryEstimated: isoDate(-2),
    miles: "465.00",
    rate: "1200.00",
    carrierPay: "1000.00",
    fuelSurcharge: "75.00",
    ratePerMile: "2.5806",
    freightType: "Auto Transport",
    equipmentType: "Open 4-Car",
    weight: "4200.00",
    paymentMethod: "ACH",
    paymentStatus: "Canceled",
    dispatchInstructions: "Canceled by customer before pickup.",
    updatedAt: new Date(),
  },
];

const vehicles = [
  { id: ids.vehicles[0], loadId: ids.loads[0], vehicleNumber: 1, year: "2022", make: "Toyota", model: "Highlander XLE", type: "SUV", color: "Silver", vin: "5TDGZRBH2NS100001", lotNumber: "SEA-22001" },
  { id: ids.vehicles[1], loadId: ids.loads[1], vehicleNumber: 1, year: "2023", make: "Porsche", model: "911 Carrera", type: "Coupe", color: "Guards Red", vin: "WP0AA2A92PS100002", lotNumber: "LIM-23002" },
  { id: ids.vehicles[2], loadId: ids.loads[2], vehicleNumber: 1, year: "2021", make: "Ford", model: "F-150 Lariat", type: "Pickup", color: "Blue", vin: "1FTFW1E85MFA00003", lotNumber: "NDX-21003" },
  { id: ids.vehicles[3], loadId: ids.loads[3], vehicleNumber: 1, year: "2024", make: "Chevrolet", model: "Equinox LT", type: "SUV", color: "White", vin: "3GNAXUEG2RL100004", lotNumber: "RFC-24004" },
  { id: ids.vehicles[4], loadId: ids.loads[3], vehicleNumber: 2, year: "2024", make: "Chevrolet", model: "Malibu RS", type: "Sedan", color: "Black", vin: "1G1ZG5ST4RF100005", lotNumber: "RFC-24005" },
  { id: ids.vehicles[5], loadId: ids.loads[4], vehicleNumber: 1, year: "2023", make: "Mercedes-Benz", model: "GLE 450", type: "SUV", color: "Obsidian Black", vin: "4JGFB5KB7PA100006", lotNumber: "ODH-23006" },
  { id: ids.vehicles[6], loadId: ids.loads[5], vehicleNumber: 1, year: "2020", make: "Nissan", model: "Altima SV", type: "Sedan", color: "Gray", vin: "1N4BL4DV7LC100007", lotNumber: "DAC-20007" },
  { id: ids.vehicles[7], loadId: ids.loads[6], vehicleNumber: 1, year: "2022", make: "Honda", model: "Pilot Touring", type: "SUV", color: "White", vin: "5FNYF6H96NB100008", lotNumber: "CDE-22008" },
  { id: ids.vehicles[8], loadId: ids.loads[7], vehicleNumber: 1, year: "2021", make: "BMW", model: "X5 xDrive40i", type: "SUV", color: "Black", vin: "5UXCR6C08M9100009", lotNumber: "TWA-21009" },
];

const invoices = [
  {
    id: ids.invoices[0],
    invoiceNumber: "INV-DEV-0001",
    carrierId: ids.carriers[0],
    issueDate: isoDate(-7),
    dueDate: isoDate(0),
    subtotal: "3100.00",
    commissionRate: "5.00",
    total: "155.00",
    status: "Fully Paid",
    notes: "Commission for delivered premium vehicle loads.",
    updatedAt: new Date(),
  },
  {
    id: ids.invoices[1],
    invoiceNumber: "INV-DEV-0002",
    carrierId: ids.carriers[1],
    issueDate: isoDate(-5),
    dueDate: isoDate(10),
    subtotal: "2080.00",
    commissionRate: "5.00",
    total: "104.00",
    status: "Partially Paid",
    notes: "Commission for completed and active fleet assignments.",
    updatedAt: new Date(),
  },
  {
    id: ids.invoices[2],
    invoiceNumber: "INV-DEV-0003",
    carrierId: ids.carriers[2],
    issueDate: isoDate(-1),
    dueDate: isoDate(14),
    subtotal: "875.00",
    commissionRate: "6.00",
    total: "52.50",
    status: "Pending",
    notes: "Initial commission invoice during onboarding period.",
    updatedAt: new Date(),
  },
];

const invoiceLoads = [
  { id: ids.invoiceLoads[0], invoiceId: ids.invoices[0], loadId: ids.loads[0] },
  { id: ids.invoiceLoads[1], invoiceId: ids.invoices[0], loadId: ids.loads[1] },
  { id: ids.invoiceLoads[2], invoiceId: ids.invoices[1], loadId: ids.loads[2] },
  { id: ids.invoiceLoads[3], invoiceId: ids.invoices[1], loadId: ids.loads[3] },
  { id: ids.invoiceLoads[4], invoiceId: ids.invoices[2], loadId: ids.loads[5] },
];

const payments = [
  {
    id: ids.payments[0],
    invoiceId: ids.invoices[0],
    paymentDate: isoDate(-2),
    amount: "155.00",
    paymentMethod: "ACH",
    reference: "DEV-ACH-1001",
    notes: "Paid in full.",
  },
  {
    id: ids.payments[1],
    invoiceId: ids.invoices[1],
    paymentDate: isoDate(-1),
    amount: "50.00",
    paymentMethod: "Zelle",
    reference: "DEV-ZELLE-1002",
    notes: "Partial payment; remaining balance due under Net 15 terms.",
  },
];

const transactions = [
  {
    id: ids.transactions[0],
    transactionId: "TXN-DEV-0001",
    date: isoDate(-2),
    dueDate: isoDate(0),
    type: "Income",
    category: "Commission",
    description: "Commission payment for INV-DEV-0001",
    carrierId: ids.carriers[0],
    invoiceId: ids.invoices[0],
    paymentMethod: "ACH",
    amount: "155.00",
    status: "Cleared",
    referenceNumber: "DEV-ACH-1001",
    notes: "Seeded cleared commission income.",
    updatedAt: new Date(),
  },
  {
    id: ids.transactions[1],
    transactionId: "TXN-DEV-0002",
    date: isoDate(-1),
    dueDate: isoDate(10),
    type: "Income",
    category: "Commission",
    description: "Partial commission payment for INV-DEV-0002",
    carrierId: ids.carriers[1],
    invoiceId: ids.invoices[1],
    paymentMethod: "Zelle",
    amount: "50.00",
    status: "Cleared",
    referenceNumber: "DEV-ZELLE-1002",
    notes: "Seeded partial commission income.",
    updatedAt: new Date(),
  },
  {
    id: ids.transactions[2],
    transactionId: "TXN-DEV-0003",
    date: isoDate(0),
    dueDate: isoDate(14),
    type: "Income",
    category: "Commission",
    description: "Pending commission for INV-DEV-0003",
    carrierId: ids.carriers[2],
    invoiceId: ids.invoices[2],
    paymentMethod: "ACH",
    amount: "52.50",
    status: "Pending",
    referenceNumber: null,
    notes: "Pending seed commission.",
    updatedAt: new Date(),
  },
  {
    id: ids.transactions[3],
    transactionId: "TXN-DEV-0004",
    date: isoDate(-6),
    dueDate: null,
    type: "Expense",
    category: "Software",
    description: "Development dispatch software subscription",
    carrierId: null,
    invoiceId: null,
    paymentMethod: "Credit Card",
    amount: "89.00",
    status: "Cleared",
    referenceNumber: "DEV-SOFT-1004",
    notes: "Development-only expense record.",
    updatedAt: new Date(),
  },
  {
    id: ids.transactions[4],
    transactionId: "TXN-DEV-0005",
    date: isoDate(-4),
    dueDate: null,
    type: "Expense",
    category: "Communications",
    description: "Business phone and messaging services",
    carrierId: null,
    invoiceId: null,
    paymentMethod: "ACH",
    amount: "64.50",
    status: "Cleared",
    referenceNumber: "DEV-COMM-1005",
    notes: "Development-only expense record.",
    updatedAt: new Date(),
  },
  {
    id: ids.transactions[5],
    transactionId: "TXN-DEV-0006",
    date: isoDate(-3),
    dueDate: isoDate(5),
    type: "Expense",
    category: "Marketing",
    description: "Carrier recruitment campaign",
    carrierId: null,
    invoiceId: null,
    paymentMethod: "Credit Card",
    amount: "180.00",
    status: "Pending",
    referenceNumber: "DEV-MKT-1006",
    notes: "Development-only pending expense.",
    updatedAt: new Date(),
  },
];

async function seed(): Promise<void> {
  await db.transaction(async (tx) => {
    const { id: companyId, ...companySet } = companyProfile;
    await tx
      .insert(companyProfileTable)
      .values(companyProfile)
      .onConflictDoUpdate({ target: companyProfileTable.id, set: companySet });

    for (const carrier of carriers) {
      const { id, ...set } = carrier;
      await tx
        .insert(carriersTable)
        .values(carrier)
        .onConflictDoUpdate({ target: carriersTable.id, set });
    }

    for (const details of carrierDetails) {
      const { id, ...set } = details;
      await tx
        .insert(carrierContactDetailsTable)
        .values(details)
        .onConflictDoUpdate({ target: carrierContactDetailsTable.id, set });
    }

    for (const equipment of fleet) {
      const { id, ...set } = equipment;
      await tx
        .insert(carrierFleetTable)
        .values(equipment)
        .onConflictDoUpdate({ target: carrierFleetTable.id, set });
    }

    for (const details of fleetDriverDetails) {
      const { id, ...set } = details;
      await tx
        .insert(carrierFleetDriverDetailsTable)
        .values(details)
        .onConflictDoUpdate({ target: carrierFleetDriverDetailsTable.id, set });
    }

    for (const broker of brokers) {
      const { id, ...set } = broker;
      await tx
        .insert(brokersTable)
        .values(broker)
        .onConflictDoUpdate({ target: brokersTable.id, set });
    }

    for (const contact of contacts) {
      const { id, ...set } = contact;
      await tx
        .insert(crmContactsTable)
        .values(contact)
        .onConflictDoUpdate({ target: crmContactsTable.id, set });
    }

    for (const lead of leads) {
      const { id, ...set } = lead;
      await tx
        .insert(crmLeadsTable)
        .values(lead)
        .onConflictDoUpdate({ target: crmLeadsTable.id, set });
    }

    for (const driver of drivers) {
      const { id, ...set } = driver;
      await tx
        .insert(driversTable)
        .values(driver)
        .onConflictDoUpdate({ target: driversTable.id, set });
    }

    for (const load of loads) {
      const { id, ...set } = load;
      await tx
        .insert(loadsTable)
        .values(load)
        .onConflictDoUpdate({ target: loadsTable.id, set });
    }

    for (const vehicle of vehicles) {
      const { id, ...set } = vehicle;
      await tx
        .insert(loadVehiclesTable)
        .values(vehicle)
        .onConflictDoUpdate({ target: loadVehiclesTable.id, set });
    }

    for (const invoice of invoices) {
      const { id, ...set } = invoice;
      await tx
        .insert(invoicesTable)
        .values(invoice)
        .onConflictDoUpdate({ target: invoicesTable.id, set });
    }

    for (const link of invoiceLoads) {
      const { id, ...set } = link;
      await tx
        .insert(invoiceLoadsTable)
        .values(link)
        .onConflictDoUpdate({ target: invoiceLoadsTable.id, set });
    }

    for (const payment of payments) {
      const { id, ...set } = payment;
      await tx
        .insert(invoicePaymentsTable)
        .values(payment)
        .onConflictDoUpdate({ target: invoicePaymentsTable.id, set });
    }

    for (const transaction of transactions) {
      const { id, ...set } = transaction;
      await tx
        .insert(transactionsTable)
        .values(transaction)
        .onConflictDoUpdate({ target: transactionsTable.id, set });
    }

    await tx
      .insert(auditLogsTable)
      .values({
        id: ids.audit,
        actorId: "development-seed",
        actorEmail: "seed@localhost",
        action: "development.seed.completed",
        entityType: "development_dataset",
        entityId: "lander-dispatch-dev-v1",
        summary: "Created or refreshed the protected development dataset",
        metadata: {
          databaseTarget: target.databaseTarget,
          carriers: carriers.length,
          brokers: brokers.length,
          contacts: contacts.length,
          leads: leads.length,
          drivers: drivers.length,
          loads: loads.length,
          invoices: invoices.length,
          transactions: transactions.length,
        },
        createdAt: new Date(),
      })
      .onConflictDoUpdate({
        target: auditLogsTable.id,
        set: {
          summary: "Created or refreshed the protected development dataset",
          metadata: {
            databaseTarget: target.databaseTarget,
            carriers: carriers.length,
            brokers: brokers.length,
            contacts: contacts.length,
            leads: leads.length,
            drivers: drivers.length,
            loads: loads.length,
            invoices: invoices.length,
            transactions: transactions.length,
          },
          createdAt: new Date(),
        },
      });

    void companyId;
  });
}

try {
  await seed();
  console.log(
    `Development seed completed on ${target.databaseTarget} (${target.isLocal ? "local" : "allowlisted remote dev"}).`,
  );
  console.log(
    `Seeded ${carriers.length} carriers, ${brokers.length} brokers, ${contacts.length} contacts, ${leads.length} leads, ${drivers.length} drivers, ${loads.length} loads, ${invoices.length} invoices and ${transactions.length} transactions.`,
  );
} finally {
  await pool.end();
}
