import { CalendarDays, Clock, MapPin, Pencil, Users } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/shared/components/ui/dialog";
import type { AgendaEvent } from "./SchedulerFormModal";

export function SchedulerViewModal({ event, onOpenChange, onEdit }: { event: AgendaEvent | null; onOpenChange: (open: boolean) => void; onEdit: (event: AgendaEvent) => void }) {
  if (!event) return null;
  return <Dialog open={Boolean(event)} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader><div className="flex items-start justify-between gap-4"><div><DialogTitle>{event.title}</DialogTitle><p className="mt-1 text-sm text-slate-500">{event.type} · {event.status}</p></div><Button size="sm" variant="outline" className="gap-2" onClick={() => onEdit(event)}><Pencil className="h-4 w-4" />Edit</Button></div></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Info icon={CalendarDays} label="Schedule" value={`${event.startDate} ${event.startTime || ""}${event.endDate ? ` → ${event.endDate} ${event.endTime || ""}` : ""}`} /><Info icon={Clock} label="Status" value={event.status} /><Info icon={Users} label="Participants" value={event.participants.join(", ") || "No participants"} /><Info icon={MapPin} label="Location" value={[event.locationName, event.address].filter(Boolean).join(" · ") || "No location"} /></div><div className="grid gap-4 sm:grid-cols-3"><Info label="Capacity" value={event.capacity || "—"} /><Info label="Fee / Cost" value={event.fee ? `$${event.fee}` : "—"} /><Info label="Expected Audience" value={event.expectedAudience || "—"} /></div><section><p className="text-xs font-medium text-slate-500">Description</p><div className="mt-1.5 rounded-lg border border-slate-200 bg-slate-50/50 p-3 text-sm">{event.description || "No description."}</div></section><section><p className="text-xs font-medium text-slate-500">Notes</p><div className="mt-1.5 rounded-lg border border-slate-200 bg-slate-50/50 p-3 text-sm">{event.notes || "No notes."}</div></section></DialogContent></Dialog>;
}
function Info({ icon: Icon, label, value }: { icon?: typeof CalendarDays; label: string; value: string }) { return <div className="rounded-lg border border-slate-200 bg-slate-50/50 p-3"><div className="flex items-center gap-2 text-xs font-medium text-slate-500">{Icon ? <Icon className="h-3.5 w-3.5" /> : null}{label}</div><p className="mt-1.5 text-sm font-medium text-[#0B1E36]">{value}</p></div>; }
