import { useMemo, useState } from "react";
import { Archive, CheckCircle2, Clock3, MessageCircle, MoreHorizontal, Phone, Plus, Search, Send, Tag, UserRound, Users } from "lucide-react";
import { Button } from "@/shared/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/shared/components/ui/dialog";
import { Input } from "@/shared/components/ui/input";
import { Label } from "@/shared/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/shared/components/ui/tabs";
import { Textarea } from "@/shared/components/ui/textarea";
import { usePersistentState } from "@/shared/hooks/usePersistentState";
import type { ChatMessage, SupportChannel, SupportConversation, SupportStatus } from "../types";

const CHANNELS: SupportChannel[] = ["WhatsApp", "Instagram", "Facebook", "Email", "Website"];
const STATUSES: SupportStatus[] = ["Open", "Pending", "Waiting", "Closed"];
const TEAM = ["Unassigned", "Dispatch", "Operations", "Accounting", "Admin"];

export function SupportCenterView({ onRequestNew }: { onRequestNew: () => void }) {
  const [conversations, setConversations] = usePersistentState<SupportConversation[]>("lander:chat-support", []);
  const [selectedId, setSelectedId] = useState("");
  const [search, setSearch] = useState("");
  const [channel, setChannel] = useState("all");
  const [status, setStatus] = useState("all");
  const [draft, setDraft] = useState("");
  const [noteDraft, setNoteDraft] = useState("");
  const [tagDraft, setTagDraft] = useState("");
  const [sideTab, setSideTab] = useState("details");
  const selected = conversations.find((c) => c.id === selectedId) ?? conversations[0] ?? null;
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return conversations.filter((c) => (!q || `${c.contactName} ${c.protocol} ${c.tags.join(" ")}`.toLowerCase().includes(q)) && (channel === "all" || c.channel === channel) && (status === "all" || c.status === status)); }, [conversations, search, channel, status]);
  const patch = (id: string, next: Partial<SupportConversation>) => setConversations((current) => current.map((c) => c.id === id ? { ...c, ...next, updatedAt: new Date().toISOString() } : c));
  const send = () => { if (!selected || !draft.trim() || selected.status === "Closed") return; const message: ChatMessage = { id: crypto.randomUUID(), sender: "self", senderName: "Support", body: draft.trim(), at: new Date().toISOString() }; patch(selected.id, { messages: [...selected.messages, message] }); setDraft(""); };
  const addNote = () => { if (!selected || !noteDraft.trim()) return; const note: ChatMessage = { id: crypto.randomUUID(), sender: "self", senderName: "Internal note", body: noteDraft.trim(), at: new Date().toISOString(), kind: "note" }; patch(selected.id, { internalNotes: [...selected.internalNotes, note] }); setNoteDraft(""); };
  const addTag = () => { if (!selected || !tagDraft.trim()) return; patch(selected.id, { tags: [...new Set([...selected.tags, tagDraft.trim()])] }); setTagDraft(""); };

  return <div className="grid h-[calc(100vh-248px)] min-h-[590px] grid-cols-[310px_minmax(0,1fr)_280px] gap-4">
    <section className="flex flex-col overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="space-y-3 border-b border-slate-200 p-4"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-base font-semibold"><MessageCircle className="h-4 w-4" />Support Queue</h2><Button size="sm" className="h-8 gap-1.5 text-xs" onClick={onRequestNew}><Plus className="h-3.5 w-3.5" />New</Button></div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input className="pl-9" placeholder="Search client, protocol or tag..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="grid grid-cols-2 gap-2"><Select value={channel} onValueChange={setChannel}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All channels</SelectItem>{CHANNELS.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{STATUSES.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div></div><div className="min-h-0 flex-1 overflow-y-auto">{filtered.length === 0 ? <div className="px-5 py-10 text-center"><MessageCircle className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 text-sm font-medium">No support conversations</p><p className="mt-1 text-xs text-slate-500">Start a WhatsApp conversation from the New button.</p></div> : filtered.map((conversation) => <button key={conversation.id} type="button" onClick={() => setSelectedId(conversation.id)} className={`w-full border-b border-slate-200 p-3 text-left hover:bg-slate-50 ${selected?.id === conversation.id ? "bg-blue-50" : ""}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-medium">{conversation.contactName || conversation.phone}</p><p className="mt-0.5 text-[11px] text-slate-500">{conversation.protocol} · {conversation.channel}</p></div><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${conversation.status === "Closed" ? "bg-slate-100 text-slate-500" : conversation.status === "Open" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{conversation.status}</span></div><div className="mt-2 flex flex-wrap gap-1">{conversation.tags.slice(0,3).map((tag) => <span key={tag} className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-500">{tag}</span>)}</div></button>)}</div></section>

    <section className="flex min-w-0 flex-col overflow-hidden rounded-lg border border-slate-200 bg-white">{!selected ? <div className="flex h-full flex-col items-center justify-center text-center"><MessageCircle className="mb-4 h-16 w-16 text-slate-300" /><h3 className="text-lg font-semibold">Select a support conversation</h3><p className="mt-2 max-w-sm text-sm text-slate-500">Choose a conversation in the queue or start a new WhatsApp conversation.</p></div> : <><div className="flex items-center justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h3 className="font-semibold">{selected.contactName || selected.phone}</h3><p className="text-xs text-slate-500">{selected.channel} · {selected.protocol}</p></div><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={selected.status === "Closed"} onClick={() => patch(selected.id, { status: "Pending" })}><Clock3 className="mr-1.5 h-3.5 w-3.5" />Pending</Button><Button size="sm" disabled={selected.status === "Closed"} onClick={() => patch(selected.id, { status: "Closed" })}><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Finalize</Button></div></div><div className="min-h-0 flex-1 overflow-y-auto bg-slate-50/50 p-5"><div className="space-y-4">{selected.messages.map((message) => <div key={message.id} className={`flex ${message.sender === "self" ? "justify-end" : "justify-start"}`}><div className={`max-w-[72%] rounded-lg px-3 py-2 shadow-sm ${message.sender === "self" ? "bg-[#1E3D7A] text-white" : "border border-slate-200 bg-white"}`}><p className="text-sm">{message.body}</p><p className="mt-1 text-[10px] opacity-60">{new Date(message.at).toLocaleString()}</p></div></div>)}</div></div>{selected.status === "Closed" ? <div className="border-t border-slate-200 p-4 text-center"><p className="text-sm text-slate-500">Conversation finalized.</p><Button variant="outline" size="sm" className="mt-2" onClick={() => patch(selected.id, { status: "Open" })}>Reopen</Button></div> : <div className="border-t border-slate-200 p-4"><Textarea placeholder="Type a message to the client..." className="min-h-[78px] resize-none" value={draft} onChange={(e) => setDraft(e.target.value)} /><div className="mt-3 flex items-center justify-between"><div className="flex gap-2"><Button variant="outline" size="sm" disabled><Phone className="mr-1.5 h-3.5 w-3.5" />Audio</Button><Button variant="outline" size="sm" disabled><MoreHorizontal className="mr-1.5 h-3.5 w-3.5" />Quick replies</Button></div><Button size="sm" className="gap-1.5" disabled={!draft.trim()} onClick={send}><Send className="h-3.5 w-3.5" />Send</Button></div></div>}</>}</section>

    <aside className="overflow-hidden rounded-lg border border-slate-200 bg-white"><Tabs value={sideTab} onValueChange={setSideTab}><TabsList className="m-3 grid w-[calc(100%-1.5rem)] grid-cols-2"><TabsTrigger value="details">Details</TabsTrigger><TabsTrigger value="notes">Notes</TabsTrigger></TabsList><TabsContent value="details" className="m-0 space-y-4 p-4 pt-1">{selected ? <><Detail icon={UserRound} label="Contact" value={selected.contactName || "Unnamed"} /><Detail icon={Phone} label="Phone" value={selected.phone} /><div><Label className="text-xs">Assignee</Label><Select value={selected.assignee} onValueChange={(value) => patch(selected.id, { assignee: value })}><SelectTrigger className="mt-1.5 h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent>{TEAM.map((member) => <SelectItem key={member} value={member}>{member}</SelectItem>)}</SelectContent></Select></div><div><Label className="text-xs">Status</Label><Select value={selected.status} onValueChange={(value) => patch(selected.id, { status: value as SupportStatus })}><SelectTrigger className="mt-1.5 h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent>{STATUSES.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><Tag className="h-3.5 w-3.5" />Tags</div><div className="mt-2 flex flex-wrap gap-1">{selected.tags.map((tag) => <button key={tag} className="rounded-full border border-slate-200 px-2 py-1 text-[10px]" onClick={() => patch(selected.id, { tags: selected.tags.filter((item) => item !== tag) })}>{tag} ×</button>)}</div><div className="mt-2 flex gap-2"><Input className="h-8 text-xs" placeholder="Ex.: Priority" value={tagDraft} onChange={(e) => setTagDraft(e.target.value)} /><Button size="sm" className="h-8" disabled={!tagDraft.trim()} onClick={addTag}>Add</Button></div></div><Button variant="outline" className="w-full" onClick={() => patch(selected.id, { status: "Closed" })}><Archive className="mr-2 h-4 w-4" />Archive conversation</Button></> : null}</TabsContent><TabsContent value="notes" className="m-0 p-4 pt-1">{selected ? <><Textarea rows={4} placeholder="Internal note..." value={noteDraft} onChange={(e) => setNoteDraft(e.target.value)} /><Button size="sm" className="mt-2 w-full" disabled={!noteDraft.trim()} onClick={addNote}>Add internal note</Button><div className="mt-4 space-y-2">{selected.internalNotes.map((note) => <div key={note.id} className="rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-xs text-amber-900">{note.body}</p><p className="mt-1 text-[10px] text-amber-700">{new Date(note.at).toLocaleString()}</p></div>)}</div></> : null}</TabsContent></Tabs></aside>
  </div>;
}
function Detail({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <div><div className="flex items-center gap-2 text-xs text-slate-500"><Icon className="h-3.5 w-3.5" />{label}</div><p className="mt-1 text-sm font-medium">{value}</p></div>; }

export function NewSupportConversationDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [conversations, setConversations] = usePersistentState<SupportConversation[]>("lander:chat-support", []);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [message, setMessage] = useState("");
  const create = () => { if (!phone.trim()) return; const now = new Date().toISOString(); const conversation: SupportConversation = { id: crypto.randomUUID(), protocol: `SUP-${String(conversations.length + 1).padStart(5,"0")}`, contactName: name.trim(), phone: phone.trim(), channel: "WhatsApp", status: "Open", assignee: "Unassigned", originLabel: "Manual WhatsApp", tags: [], messages: message.trim() ? [{ id: crypto.randomUUID(), sender: "self", senderName: "Support", body: message.trim(), at: now }] : [], internalNotes: [], createdAt: now, updatedAt: now, priority: "Normal", deadline: "" }; setConversations((current) => [conversation, ...current]); setName(""); setPhone(""); setMessage(""); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>New conversation via WhatsApp</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Contact name</Label><Input className="mt-1.5" value={name} onChange={(e) => setName(e.target.value)} placeholder="Optional" /></div><div><Label>Phone (WhatsApp) *</Label><Input className="mt-1.5" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+1 555 000 0000" /></div><div><Label>Initial message</Label><Textarea className="mt-1.5" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Optional — conversation can be created without sending anything yet" /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={create} disabled={!phone.trim()}>Create conversation</Button></DialogFooter></DialogContent></Dialog>;
}
