import { mockDate } from "./date";

export function createMockAgendaEvents() {
  return [
    {
      id: "mock-agenda-001",
      title: "Pickup coordination — LD-24091",
      type: "Pickup",
      participants: ["Dispatch", "Blue Ridge Auto Transport", "Marcus Reed"],
      status: "Confirmed",
      startDate: mockDate(0),
      startTime: "08:30",
      endDate: mockDate(0),
      endTime: "09:00",
      locationName: "Manheim Charlotte",
      locationContact: "(704) 555-0124",
      address: "Charlotte, NC",
      capacity: "",
      fee: "",
      expectedAudience: "3",
      description: "Confirm vehicle release, gate pass and driver arrival window.",
      notes: "Driver must send pickup photos before departure.",
    },
    {
      id: "mock-agenda-002",
      title: "Broker onboarding call — Apex Auto Logistics",
      type: "Meeting",
      participants: ["Operations", "Accounting", "Apex Auto Logistics"],
      status: "Scheduled",
      startDate: mockDate(1),
      startTime: "11:00",
      endDate: mockDate(1),
      endTime: "11:45",
      locationName: "Google Meet",
      locationContact: "",
      address: "",
      capacity: "",
      fee: "",
      expectedAudience: "4",
      description: "Review payment terms, dispatch workflow and escalation contacts.",
      notes: "Prepare W-9, insurance requirements and QuickPay discussion.",
    },
    {
      id: "mock-agenda-003",
      title: "Delivery follow-up — LD-24088",
      type: "Delivery",
      participants: ["Dispatch", "Coastal Carriers LLC", "Summit Motors"],
      status: "Pending",
      startDate: mockDate(2),
      startTime: "15:30",
      endDate: mockDate(2),
      endTime: "16:00",
      locationName: "Summit Motors",
      locationContact: "(919) 555-0178",
      address: "Raleigh, NC",
      capacity: "",
      fee: "",
      expectedAudience: "3",
      description: "Confirm ETA, delivery inspection and signed BOL.",
      notes: "Customer requested 30-minute arrival notice.",
    },
    {
      id: "mock-agenda-004",
      title: "Carrier compliance review",
      type: "Inspection",
      participants: ["Compliance", "Piedmont Vehicle Transport"],
      status: "Confirmed",
      startDate: mockDate(4),
      startTime: "10:00",
      endDate: mockDate(4),
      endTime: "10:45",
      locationName: "Lander Dispatch",
      locationContact: "",
      address: "",
      capacity: "",
      fee: "",
      expectedAudience: "2",
      description: "Review authority, insurance expiration and driver qualification documents.",
      notes: "TWIC renewal evidence still pending.",
    },
    {
      id: "mock-agenda-005",
      title: "Weekly operations review",
      type: "Meeting",
      participants: ["Dispatch", "Operations", "Accounting"],
      status: "Confirmed",
      startDate: mockDate(6),
      startTime: "09:00",
      endDate: mockDate(6),
      endTime: "10:00",
      locationName: "Operations Room",
      locationContact: "",
      address: "",
      capacity: "8",
      fee: "",
      expectedAudience: "5",
      description: "Review active loads, exceptions, receivables and next-week capacity.",
      notes: "Bring unresolved task list and overdue invoice report.",
    },
    {
      id: "mock-agenda-006",
      title: "Post-delivery customer check-in",
      type: "Follow-up",
      participants: ["CRM", "Northstar Auto Group"],
      status: "Completed",
      startDate: mockDate(-1),
      startTime: "14:00",
      endDate: mockDate(-1),
      endTime: "14:20",
      locationName: "Phone",
      locationContact: "(336) 555-0192",
      address: "",
      capacity: "",
      fee: "",
      expectedAudience: "2",
      description: "Confirm delivery satisfaction and identify next transport opportunities.",
      notes: "Customer expects two auction pickups next week.",
    },
  ];
}
