import { mockDate, mockDateTime } from "./date";

export type MockApiState = ReturnType<typeof createMockApiState>;

export function createMockApiState() {
  const carriers = [
    {
      id:"mock-carrier-blue-ridge",companyName:"Blue Ridge Auto Transport",carrierType:"Owner Operator",website:"https://example.com/blue-ridge",usdotNumber:"3842107",mcNumber:"MC-138420",einNumber:"88-4201071",status:"Active",priority:"High",rating:4.9,tags:["Preferred","Enclosed capable"],notes:"Strong Southeast lane coverage and fast communication.",primaryContact:"Eric Lawson",phone:"(704) 555-0188",email:"dispatch@blueridge.example",lastContact:mockDateTime(0,8,10),companyAddress:"1250 Logistics Way",companyCity:"Charlotte",companyState:"NC",companyZip:"28208",fleetSize:4,trucks:4,trailers:4,drivers:4,operatingStates:["NC","SC","GA","VA","TN"],serviceTypes:["Open Transport","Enclosed Transport"],ratePerMile:1.18,insuranceExpiration:mockDate(78),authorityStatus:"Active",paymentTerms:"Net 7",quickPay:true,factoringCompany:null,factoringFee:null,bankName:"First Carolina Bank",accountHolder:"Blue Ridge Auto Transport LLC",accountNumberLast4:"4821",routingNumberLast4:"0194",bankCity:"Charlotte",bankState:"NC",zelleAccount:"payments@blueridge.example",cashAppAccount:null,lastLoadDate:mockDate(-1),createdAt:mockDateTime(-180,10),updatedAt:mockDateTime(0,8)
    },
    {
      id:"mock-carrier-piedmont",companyName:"Piedmont Vehicle Transport",carrierType:"Small Fleet",website:"https://example.com/piedmont",usdotNumber:"3715620",mcNumber:"MC-129775",einNumber:"85-7156204",status:"Active",priority:"Medium",rating:4.6,tags:["Compliance review"],notes:"Reliable regional fleet. Updated COI pending review.",primaryContact:"Nina Brooks",phone:"(336) 555-0141",email:"ops@piedmont.example",lastContact:mockDateTime(-1,15,20),companyAddress:"880 Commerce Park Dr",companyCity:"Greensboro",companyState:"NC",companyZip:"27409",fleetSize:7,trucks:7,trailers:6,drivers:8,operatingStates:["NC","SC","VA","WV"],serviceTypes:["Open Transport"],ratePerMile:1.12,insuranceExpiration:mockDate(12),authorityStatus:"Active",paymentTerms:"Net 15",quickPay:false,factoringCompany:"Roadway Capital",factoringFee:2.5,bankName:"Piedmont Community Bank",accountHolder:"Piedmont Vehicle Transport Inc",accountNumberLast4:"2906",routingNumberLast4:"7220",bankCity:"Greensboro",bankState:"NC",zelleAccount:null,cashAppAccount:null,lastLoadDate:mockDate(-3),createdAt:mockDateTime(-260,11),updatedAt:mockDateTime(-1,15)
    },
    {
      id:"mock-carrier-coastal",companyName:"Coastal Carriers LLC",carrierType:"Owner Operator",website:"",usdotNumber:"3590084",mcNumber:"MC-118407",einNumber:"84-5900842",status:"Inactive",priority:"Low",rating:4.3,tags:["Coastal lanes"],notes:"Temporarily inactive while equipment is under maintenance.",primaryContact:"Andre Miles",phone:"(910) 555-0163",email:"andre@coastalcarriers.example",lastContact:mockDateTime(-8,13),companyAddress:"42 Portside Blvd",companyCity:"Wilmington",companyState:"NC",companyZip:"28401",fleetSize:2,trucks:2,trailers:2,drivers:2,operatingStates:["NC","SC","GA","FL"],serviceTypes:["Open Transport"],ratePerMile:1.22,insuranceExpiration:mockDate(95),authorityStatus:"Active",paymentTerms:"Net 7",quickPay:true,factoringCompany:null,factoringFee:null,bankName:"Cape Fear Bank",accountHolder:"Coastal Carriers LLC",accountNumberLast4:"7714",routingNumberLast4:"6631",bankCity:"Wilmington",bankState:"NC",zelleAccount:"andre@coastalcarriers.example",cashAppAccount:"$CoastalCarriers",lastLoadDate:mockDate(-18),createdAt:mockDateTime(-320,9),updatedAt:mockDateTime(-8,13)
    }
  ];

  const brokers = [
    {
      id:"mock-broker-apex",companyName:"Apex Auto Logistics",brokerType:"Auto Transport Broker",website:"https://example.com/apex",mcNumber:"MC-982311",usdotNumber:"3254481",primaryContact:"Rachel Stone",phone:"(919) 555-0145",email:"loads@apex.example",lastContact:mockDateTime(-1,13),freightTypes:["Vehicles"],coverage:"National",selectedStates:["NC","SC","GA","VA","TN","FL"],paymentTerms:"Net 30",paymentDays:30,quickPay:true,quickPayFee:2,factoringAccepted:"Yes",onboardingStatus:"Approved",rating:4.8,status:"Active",priority:"High",tags:["High volume","QuickPay"],notes:"Primary broker for dealer and auction lanes.",lastLoadDate:mockDate(-1),createdAt:mockDateTime(-300,9),updatedAt:mockDateTime(-1,13)
    },
    {
      id:"mock-broker-nationwide",companyName:"Nationwide Motor Exchange",brokerType:"Dealer Logistics",website:"https://example.com/nationwide",mcNumber:"MC-760114",usdotNumber:"3022108",primaryContact:"Jason Miller",phone:"(615) 555-0129",email:"dispatch@nationwide.example",lastContact:mockDateTime(-3,10),freightTypes:["Vehicles","Dealer Transfers"],coverage:"Southeast & Midwest",selectedStates:["TN","KY","OH","NC","SC","GA"],paymentTerms:"Net 15",paymentDays:15,quickPay:false,quickPayFee:null,factoringAccepted:"Yes",onboardingStatus:"Approved",rating:4.5,status:"Active",priority:"Medium",tags:["Dealer network"],notes:"Consistent dealer-transfer volume.",lastLoadDate:mockDate(-4),createdAt:mockDateTime(-240,10),updatedAt:mockDateTime(-3,10)
    },
    {
      id:"mock-broker-carhaul",companyName:"CarHaul Central",brokerType:"Digital Broker",website:"https://example.com/carhaul",mcNumber:"MC-651830",usdotNumber:"2987410",primaryContact:"Melissa Grant",phone:"(404) 555-0181",email:"ops@carhaulcentral.example",lastContact:mockDateTime(-10,16),freightTypes:["Vehicles"],coverage:"National",selectedStates:["GA","FL","AL","NC","SC"],paymentTerms:"Net 30",paymentDays:30,quickPay:true,quickPayFee:3,factoringAccepted:"Conditional",onboardingStatus:"Review",rating:4.1,status:"Active",priority:"Low",tags:["Spot freight"],notes:"Use for backhaul opportunities when margin is acceptable.",lastLoadDate:mockDate(-12),createdAt:mockDateTime(-190,12),updatedAt:mockDateTime(-10,16)
    }
  ];

  const loads = [
    {
      id:"mock-load-001",loadId:"LD-24091",carrierId:"mock-carrier-blue-ridge",carrierName:"Blue Ridge Auto Transport",brokerId:"mock-broker-apex",brokerName:"Apex Auto Logistics",status:"Dispatched",dispatchDate:mockDate(0),pickupCity:"Charlotte",pickupState:"NC",pickupZip:"28273",pickupEstimated:mockDate(0),pickupDeadline:mockDate(0),deliveryCity:"Raleigh",deliveryState:"NC",deliveryZip:"27604",deliveryEstimated:mockDate(1),deliveryDeadline:mockDate(1),miles:168,rate:925,ratePerMile:5.51,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2023",make:"BMW",model:"X5",type:"SUV",color:"Black",plate:null,vin:"5UXCR6C0XP9K24091",lotNumber:"CLT-88214",additionalInfo:"Runs and drives",buyerNumber:"B-4902"}],dispatchInstructions:"Send pickup condition photos before departure.",pickupInstructions:"Check in at Gate 3 with buyer number.",deliveryInstructions:"Call customer 30 minutes before arrival.",createdAt:mockDateTime(-2,11),updatedAt:mockDateTime(0,8),pickupName:"Manheim Charlotte",pickupAddress:"Charlotte, NC",pickupPhone:"(704) 555-0124",pickupContactName:"Gate Office",pickupEmail:"",deliveryName:"Northstar Auto Group",deliveryAddress:"Raleigh, NC",deliveryPhone:"(919) 555-0112",deliveryContactName:"Kevin Moore",deliveryEmail:"receiving@northstar.example",carrierPay:710,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:5200,paymentStatus:"Pending"
    },
    {
      id:"mock-load-002",loadId:"LD-24090",carrierId:"mock-carrier-piedmont",carrierName:"Piedmont Vehicle Transport",brokerId:"mock-broker-nationwide",brokerName:"Nationwide Motor Exchange",status:"In Route",dispatchDate:mockDate(-1),pickupCity:"Greensboro",pickupState:"NC",pickupZip:"27409",pickupEstimated:mockDate(-1),pickupDeadline:mockDate(-1),deliveryCity:"Nashville",deliveryState:"TN",deliveryZip:"37210",deliveryEstimated:mockDate(1),deliveryDeadline:mockDate(2),miles:451,rate:1650,ratePerMile:3.66,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2022",make:"Ford",model:"F-150",type:"Truck",color:"White",plate:null,vin:"1FTFW1E59NFA24090",lotNumber:"GSO-4418",additionalInfo:"Dealer transfer",buyerNumber:null}],dispatchInstructions:"Provide midday status update.",pickupInstructions:"Dealer release at service entrance.",deliveryInstructions:"Deliver during receiving hours.",createdAt:mockDateTime(-3,14),updatedAt:mockDateTime(0,7),pickupName:"Triad Ford",pickupAddress:"Greensboro, NC",pickupPhone:"(336) 555-0105",pickupContactName:"Service Desk",pickupEmail:"",deliveryName:"Music City Auto",deliveryAddress:"Nashville, TN",deliveryPhone:"(615) 555-0166",deliveryContactName:"Receiving",deliveryEmail:"",carrierPay:1320,fuelSurcharge:75,freightType:"Vehicle",equipmentType:"Open Carrier",weight:5300,paymentStatus:"Pending"
    },
    {
      id:"mock-load-003",loadId:"LD-24089",carrierId:"mock-carrier-blue-ridge",carrierName:"Blue Ridge Auto Transport",brokerId:"mock-broker-apex",brokerName:"Apex Auto Logistics",status:"Picked Up",dispatchDate:mockDate(-1),pickupCity:"Rock Hill",pickupState:"SC",pickupZip:"29730",pickupEstimated:mockDate(-1),pickupDeadline:mockDate(-1),deliveryCity:"Savannah",deliveryState:"GA",deliveryZip:"31408",deliveryEstimated:mockDate(2),deliveryDeadline:mockDate(2),miles:214,rate:1125,ratePerMile:5.26,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2024",make:"Toyota",model:"Camry",type:"Sedan",color:"Silver",plate:null,vin:"4T1G11AK5RU240089",lotNumber:"RH-9011",additionalInfo:null,buyerNumber:"D-188"}],dispatchInstructions:null,pickupInstructions:"Photo VIN and odometer.",deliveryInstructions:"Signature required.",createdAt:mockDateTime(-2,16),updatedAt:mockDateTime(-1,18),pickupName:"Southline Auction",pickupAddress:"Rock Hill, SC",pickupPhone:"(803) 555-0174",pickupContactName:"Release Desk",pickupEmail:"",deliveryName:"Savannah Imports",deliveryAddress:"Savannah, GA",deliveryPhone:"(912) 555-0130",deliveryContactName:"Mike Hale",deliveryEmail:"",carrierPay:855,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:3400,paymentStatus:"Pending"
    },
    {
      id:"mock-load-004",loadId:"LD-24088",carrierId:"mock-carrier-piedmont",carrierName:"Piedmont Vehicle Transport",brokerId:"mock-broker-apex",brokerName:"Apex Auto Logistics",status:"Delivered",dispatchDate:mockDate(-4),pickupCity:"Richmond",pickupState:"VA",pickupZip:"23234",pickupEstimated:mockDate(-4),pickupDeadline:mockDate(-4),deliveryCity:"Raleigh",deliveryState:"NC",deliveryZip:"27617",deliveryEstimated:mockDate(-2),deliveryDeadline:mockDate(-2),miles:171,rate:980,ratePerMile:5.73,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2021",make:"Mercedes-Benz",model:"GLC 300",type:"SUV",color:"Blue",plate:null,vin:"W1N0G8EB8MV240088",lotNumber:null,additionalInfo:null,buyerNumber:null}],dispatchInstructions:null,pickupInstructions:null,deliveryInstructions:"Signed BOL required.",createdAt:mockDateTime(-5,9),updatedAt:mockDateTime(-2,15),pickupName:"Richmond Luxury Cars",pickupAddress:"Richmond, VA",pickupPhone:"(804) 555-0113",pickupContactName:"Alex Reed",pickupEmail:"",deliveryName:"Summit Motors",deliveryAddress:"Raleigh, NC",deliveryPhone:"(919) 555-0178",deliveryContactName:"Susan Price",deliveryEmail:"",carrierPay:760,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:4100,paymentStatus:"Invoiced"
    },
    {
      id:"mock-load-005",loadId:"LD-24087",carrierId:"mock-carrier-blue-ridge",carrierName:"Blue Ridge Auto Transport",brokerId:"mock-broker-nationwide",brokerName:"Nationwide Motor Exchange",status:"Delivered",dispatchDate:mockDate(-8),pickupCity:"Atlanta",pickupState:"GA",pickupZip:"30354",pickupEstimated:mockDate(-8),pickupDeadline:mockDate(-8),deliveryCity:"Charlotte",deliveryState:"NC",deliveryZip:"28208",deliveryEstimated:mockDate(-6),deliveryDeadline:mockDate(-6),miles:245,rate:1280,ratePerMile:5.22,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2020",make:"Lexus",model:"RX 350",type:"SUV",color:"White",plate:null,vin:"2T2HZMDA8LC240087",lotNumber:"ATL-10119",additionalInfo:null,buyerNumber:null}],dispatchInstructions:null,pickupInstructions:null,deliveryInstructions:null,createdAt:mockDateTime(-9,10),updatedAt:mockDateTime(-6,16),pickupName:"Atlanta Auto Exchange",pickupAddress:"Atlanta, GA",pickupPhone:"(404) 555-0120",pickupContactName:"Auction Desk",pickupEmail:"",deliveryName:"Queen City Motors",deliveryAddress:"Charlotte, NC",deliveryPhone:"(704) 555-0190",deliveryContactName:"Receiving",deliveryEmail:"",carrierPay:980,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:4380,paymentStatus:"Paid"
    },
    {
      id:"mock-load-006",loadId:"LD-24086",carrierId:null,carrierName:null,brokerId:"mock-broker-carhaul",brokerName:"CarHaul Central",status:"New",dispatchDate:null,pickupCity:"Columbia",pickupState:"SC",pickupZip:"29203",pickupEstimated:mockDate(2),pickupDeadline:mockDate(3),deliveryCity:"Jacksonville",deliveryState:"FL",deliveryZip:"32218",deliveryEstimated:mockDate(4),deliveryDeadline:mockDate(5),miles:292,rate:1425,ratePerMile:4.88,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2022",make:"Honda",model:"Accord",type:"Sedan",color:"Gray",plate:null,vin:"1HGCV1F30NA240086",lotNumber:"COL-7720",additionalInfo:"No keys in office after 5 PM",buyerNumber:null}],dispatchInstructions:"Needs carrier assignment.",pickupInstructions:null,deliveryInstructions:null,createdAt:mockDateTime(-1,12),updatedAt:null,pickupName:"Capital Auto Auction",pickupAddress:"Columbia, SC",pickupPhone:"(803) 555-0109",pickupContactName:"Release",pickupEmail:"",deliveryName:"Jax Auto Mall",deliveryAddress:"Jacksonville, FL",deliveryPhone:"(904) 555-0115",deliveryContactName:"Receiving",deliveryEmail:"",carrierPay:0,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:3300,paymentStatus:"Pending"
    },
    {
      id:"mock-load-007",loadId:"LD-24085",carrierId:"mock-carrier-piedmont",carrierName:"Piedmont Vehicle Transport",brokerId:"mock-broker-apex",brokerName:"Apex Auto Logistics",status:"Delivered",dispatchDate:mockDate(-12),pickupCity:"Roanoke",pickupState:"VA",pickupZip:"24012",pickupEstimated:mockDate(-12),pickupDeadline:mockDate(-12),deliveryCity:"Charlotte",deliveryState:"NC",deliveryZip:"28273",deliveryEstimated:mockDate(-10),deliveryDeadline:mockDate(-10),miles:197,rate:1050,ratePerMile:5.33,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2019",make:"Chevrolet",model:"Tahoe",type:"SUV",color:"Black",plate:null,vin:"1GNSKBKC7KR240085",lotNumber:null,additionalInfo:null,buyerNumber:null}],dispatchInstructions:null,pickupInstructions:null,deliveryInstructions:null,createdAt:mockDateTime(-13,8),updatedAt:mockDateTime(-10,14),pickupName:"Blue Ridge Chevrolet",pickupAddress:"Roanoke, VA",pickupPhone:"(540) 555-0182",pickupContactName:"Sales",pickupEmail:"",deliveryName:"Queen City Motors",deliveryAddress:"Charlotte, NC",deliveryPhone:"(704) 555-0190",deliveryContactName:"Receiving",deliveryEmail:"",carrierPay:810,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:5500,paymentStatus:"Paid"
    },
    {
      id:"mock-load-008",loadId:"LD-24084",carrierId:"mock-carrier-coastal",carrierName:"Coastal Carriers LLC",brokerId:"mock-broker-carhaul",brokerName:"CarHaul Central",status:"Canceled",dispatchDate:mockDate(-15),pickupCity:"Charleston",pickupState:"SC",pickupZip:"29405",pickupEstimated:mockDate(-14),pickupDeadline:mockDate(-14),deliveryCity:"Orlando",deliveryState:"FL",deliveryZip:"32824",deliveryEstimated:mockDate(-12),deliveryDeadline:mockDate(-12),miles:382,rate:1550,ratePerMile:4.06,paymentMethod:"ACH",vehicles:[{vehicleNumber:1,year:"2021",make:"Tesla",model:"Model 3",type:"Sedan",color:"Red",plate:null,vin:"5YJ3E1EA5MF240084",lotNumber:"CHS-883",additionalInfo:"Canceled before pickup",buyerNumber:null}],dispatchInstructions:"Canceled by broker.",pickupInstructions:null,deliveryInstructions:null,createdAt:mockDateTime(-16,10),updatedAt:mockDateTime(-14,9),pickupName:"Charleston EV Center",pickupAddress:"Charleston, SC",pickupPhone:"(843) 555-0121",pickupContactName:"Front Desk",pickupEmail:"",deliveryName:"Orlando EV Outlet",deliveryAddress:"Orlando, FL",deliveryPhone:"(407) 555-0170",deliveryContactName:"Receiving",deliveryEmail:"",carrierPay:0,fuelSurcharge:0,freightType:"Vehicle",equipmentType:"Open Carrier",weight:3550,paymentStatus:"Canceled"
    }
  ];

  const contacts = [
    {id:"mock-contact-northstar",companyName:"Northstar Auto Group",contactType:"Dealer",primaryContact:"Kevin Moore",phone:"(919) 555-0112",phone2:null,email:"kevin@northstar.example",website:"https://example.com/northstar",streetAddress:"4100 Capital Blvd",city:"Raleigh",state:"NC",zipCode:"27604",coverageArea:"Carolinas",businessHours:"Mon-Fri 8:00-18:00",emergencyService:false,services:"Dealer transfers and retail vehicle receiving",status:"Active",priority:"High",rating:5,lastContact:mockDateTime(-1,14),tags:["Customer","Dealer"],notes:"Recurring auction pickup opportunities.",createdAt:mockDateTime(-210,10),primaryContactName:"Kevin Moore",primaryPhoneNumber:"(919) 555-0112",primaryPhoneNumber2:null,emergencyContactName:null,emergencyPhoneNumber:null,emergencyPhoneNumber2:null,updatedAt:mockDateTime(-1,14)},
    {id:"mock-contact-manheim",companyName:"Manheim Charlotte",contactType:"Auction",primaryContact:"Release Desk",phone:"(704) 555-0124",phone2:null,email:"release@manheim-charlotte.example",website:"https://example.com/manheim",streetAddress:"7600 Auction Ln",city:"Charlotte",state:"NC",zipCode:"28273",coverageArea:"Charlotte metro",businessHours:"Mon-Fri 7:00-17:00",emergencyService:false,services:"Vehicle auction release",status:"Active",priority:"Medium",rating:4.7,lastContact:mockDateTime(0,8),tags:["Auction","Pickup"],notes:"Gate 3 handles transporter releases.",createdAt:mockDateTime(-340,9),primaryContactName:"Release Desk",primaryPhoneNumber:"(704) 555-0124",primaryPhoneNumber2:null,emergencyContactName:null,emergencyPhoneNumber:null,emergencyPhoneNumber2:null,updatedAt:mockDateTime(0,8)},
    {id:"mock-contact-roadside",companyName:"Triangle Roadside & Towing",contactType:"Towing",primaryContact:"Sam Perez",phone:"(984) 555-0128",phone2:"(984) 555-0199",email:"dispatch@triangleroadside.example",website:"",streetAddress:"880 Service Rd",city:"Durham",state:"NC",zipCode:"27703",coverageArea:"Raleigh-Durham",businessHours:"24/7",emergencyService:true,services:"Towing, jump starts, lockout support",status:"Active",priority:"Medium",rating:4.8,lastContact:mockDateTime(-6,20),tags:["Emergency","Vendor"],notes:"Preferred roadside vendor for Triangle area.",createdAt:mockDateTime(-160,13),primaryContactName:"Sam Perez",primaryPhoneNumber:"(984) 555-0128",primaryPhoneNumber2:"(984) 555-0199",emergencyContactName:"24/7 Dispatch",emergencyPhoneNumber:"(984) 555-0128",emergencyPhoneNumber2:null,updatedAt:mockDateTime(-6,20)}
  ];

  const leads = [
    {id:"mock-lead-dealer",companyName:"Carolina Premier Motors",leadType:"Dealer",primaryContact:"Laura Greene",phone:"(704) 555-0159",email:"laura@carolinapremier.example",website:"https://example.com/carolina-premier",usdotNumber:null,mcNumber:null,streetAddress:"6200 Independence Blvd",city:"Charlotte",state:"NC",zipCode:"28212",fleetSize:null,serviceTypes:["Dealer Transfers"],operatingStates:["NC","SC"],leadSource:"Referral",pipelineStage:"Proposal",estimatedWeeklyLoads:6,estimatedWeeklyRevenue:5400,priority:"High",rating:4.5,nextFollowUp:mockDateTime(1,10),nextFollowUpDate:mockDate(1),nextFollowUpTime:"10:00",followUpNotes:"Review pricing for recurring auction pickups.",lastContact:mockDateTime(-1,11),status:"Active",convertedCarrierId:null,tags:["Dealer","Warm"],notes:"Interested in weekly auction-to-dealer routes.",createdAt:mockDateTime(-18,10),updatedAt:mockDateTime(-1,11)},
    {id:"mock-lead-auction",companyName:"Upstate Auto Exchange",leadType:"Auction",primaryContact:"Brian Cole",phone:"(864) 555-0147",email:"bcole@upstateexchange.example",website:"",usdotNumber:null,mcNumber:null,streetAddress:"190 Auction Park",city:"Greenville",state:"SC",zipCode:"29605",fleetSize:null,serviceTypes:["Auction Transport"],operatingStates:["SC","NC","GA"],leadSource:"Website",pipelineStage:"Qualified",estimatedWeeklyLoads:10,estimatedWeeklyRevenue:8200,priority:"High",rating:4,nextFollowUp:mockDateTime(2,14),nextFollowUpDate:mockDate(2),nextFollowUpTime:"14:00",followUpNotes:"Needs service-level summary.",lastContact:mockDateTime(-2,16),status:"Active",convertedCarrierId:null,tags:["Auction","Inbound"],notes:"Evaluating outbound transport partner.",createdAt:mockDateTime(-11,12),updatedAt:mockDateTime(-2,16)},
    {id:"mock-lead-fleet",companyName:"Southeast Rental Fleet",leadType:"Fleet / Rental Company",primaryContact:"Monica Bell",phone:"(404) 555-0179",email:"monica@southeastrental.example",website:"https://example.com/se-rental",usdotNumber:null,mcNumber:null,streetAddress:"2550 Fleet Pkwy",city:"Atlanta",state:"GA",zipCode:"30337",fleetSize:180,serviceTypes:["Fleet Relocation"],operatingStates:["GA","FL","NC","SC"],leadSource:"Outbound",pipelineStage:"Contacted",estimatedWeeklyLoads:14,estimatedWeeklyRevenue:12000,priority:"Medium",rating:3.8,nextFollowUp:mockDateTime(4,9),nextFollowUpDate:mockDate(4),nextFollowUpTime:"09:00",followUpNotes:"Procurement review in progress.",lastContact:mockDateTime(-5,15),status:"Active",convertedCarrierId:null,tags:["Fleet","Enterprise"],notes:"Potential seasonal relocation volume.",createdAt:mockDateTime(-28,9),updatedAt:mockDateTime(-5,15)},
    {id:"mock-lead-manufacturer",companyName:"BluePeak EV Components",leadType:"Manufacturer",primaryContact:"David Huang",phone:"(423) 555-0134",email:"david@bluepeakev.example",website:"https://example.com/bluepeak",usdotNumber:null,mcNumber:null,streetAddress:"77 Innovation Dr",city:"Chattanooga",state:"TN",zipCode:"37416",fleetSize:null,serviceTypes:["Prototype Vehicle Transport"],operatingStates:["TN","GA","NC"],leadSource:"Trade Show",pipelineStage:"New",estimatedWeeklyLoads:3,estimatedWeeklyRevenue:4500,priority:"Medium",rating:3.5,nextFollowUp:mockDateTime(5,13),nextFollowUpDate:mockDate(5),nextFollowUpTime:"13:00",followUpNotes:"Send enclosed transport capability sheet.",lastContact:null,status:"Active",convertedCarrierId:null,tags:["Manufacturer","EV"],notes:"Requires high-touch prototype transport.",createdAt:mockDateTime(-6,14),updatedAt:null}
  ];

  const drivers = [
    {id:"mock-driver-marcus",fullName:"Marcus Reed",status:"Active",dateOfBirth:"1988-05-14",phoneNumber:"(704) 555-0108",email:"marcus@blueridge.example",emergencyContactName:"Tanya Reed",emergencyPhoneNumber:"(704) 555-0155",streetAddress:"100 Oak Ridge Dr",city:"Charlotte",state:"NC",zipCode:"28216",hireDate:"2023-02-06",driverType:"Company Driver",employmentType:"Full Time",yearsOfExperience:9,driverLicenseNumber:"NC-R842019",driverLicenseState:"NC",driverLicenseClass:"A",driverLicenseExpiration:mockDate(410),cdlNumber:"NC-CDL-842019",cdlState:"NC",cdlClass:"A",cdlExpiration:mockDate(410),cdlEndorsements:["T"],cdlRestrictions:null,hazmatEndorsement:false,medicalExaminerCertificateNumber:"MED-49201",medicalCardIssueDate:mockDate(-140),medicalCardExpiration:mockDate(590),medicalExaminerName:"Dr. K. Lewis",nationalRegistryNumber:"NR-881209",twicCardNumber:"TWIC-220481",twicCardExpiration:mockDate(320),driverQualificationFileStatus:"Complete",mvrCheckDate:mockDate(-45),mvrNextReviewDate:mockDate(320),mvrStatus:"Clear",backgroundCheckDate:mockDate(-240),backgroundCheckStatus:"Clear",drugTestDate:mockDate(-90),drugTestResult:"Negative",alcoholTestDate:mockDate(-90),alcoholTestResult:"Negative",clearinghouseStatus:"Clear",clearinghouseLastQueryDate:mockDate(-30),clearinghouseNextQueryDate:mockDate(335),complianceStatus:"Compliant",accidentHistory:"None reported",violationHistory:"None reported",assignedCarrierId:"mock-carrier-blue-ridge",assignedTruckId:"Truck 12",assignedTrailerId:"Trailer 8",lastLoad:"LD-24091",totalLoads:142,lastAssignmentDate:mockDate(0),notes:"Preferred for high-priority regional moves.",tags:["Experienced","Preferred"],createdAt:mockDateTime(-500,9),updatedAt:mockDateTime(0,8)},
    {id:"mock-driver-alex",fullName:"Alex Turner",status:"Active",dateOfBirth:"1991-10-22",phoneNumber:"(336) 555-0180",email:"alex@piedmont.example",emergencyContactName:"Jamie Turner",emergencyPhoneNumber:"(336) 555-0127",streetAddress:"48 Spring Creek Rd",city:"Greensboro",state:"NC",zipCode:"27407",hireDate:"2024-01-15",driverType:"Company Driver",employmentType:"Full Time",yearsOfExperience:6,driverLicenseNumber:"NC-T551408",driverLicenseState:"NC",driverLicenseClass:"A",driverLicenseExpiration:mockDate(280),cdlNumber:"NC-CDL-551408",cdlState:"NC",cdlClass:"A",cdlExpiration:mockDate(280),cdlEndorsements:["T"],cdlRestrictions:null,hazmatEndorsement:false,medicalExaminerCertificateNumber:"MED-55119",medicalCardIssueDate:mockDate(-220),medicalCardExpiration:mockDate(510),medicalExaminerName:"Dr. R. Patel",nationalRegistryNumber:"NR-772105",twicCardNumber:"TWIC-405813",twicCardExpiration:mockDate(36),driverQualificationFileStatus:"Review",mvrCheckDate:mockDate(-160),mvrNextReviewDate:mockDate(205),mvrStatus:"Clear",backgroundCheckDate:mockDate(-400),backgroundCheckStatus:"Clear",drugTestDate:mockDate(-120),drugTestResult:"Negative",alcoholTestDate:mockDate(-120),alcoholTestResult:"Negative",clearinghouseStatus:"Clear",clearinghouseLastQueryDate:mockDate(-120),clearinghouseNextQueryDate:mockDate(245),complianceStatus:"Review Required",accidentHistory:"None reported",violationHistory:"Minor speeding citation, resolved",assignedCarrierId:"mock-carrier-piedmont",assignedTruckId:"Truck 21",assignedTrailerId:"Trailer 14",lastLoad:"LD-24090",totalLoads:88,lastAssignmentDate:mockDate(-1),notes:"TWIC renewal follow-up required.",tags:["TWIC renewal"],createdAt:mockDateTime(-420,9),updatedAt:mockDateTime(-1,15)},
    {id:"mock-driver-andre",fullName:"Andre Miles",status:"Inactive",dateOfBirth:"1985-03-08",phoneNumber:"(910) 555-0163",email:"andre@coastalcarriers.example",emergencyContactName:"Monique Miles",emergencyPhoneNumber:"(910) 555-0191",streetAddress:"42 Portside Blvd",city:"Wilmington",state:"NC",zipCode:"28401",hireDate:"2021-07-01",driverType:"Owner Operator",employmentType:"Contractor",yearsOfExperience:12,driverLicenseNumber:"NC-M482201",driverLicenseState:"NC",driverLicenseClass:"A",driverLicenseExpiration:mockDate(160),cdlNumber:"NC-CDL-482201",cdlState:"NC",cdlClass:"A",cdlExpiration:mockDate(160),cdlEndorsements:["T"],cdlRestrictions:null,hazmatEndorsement:false,medicalExaminerCertificateNumber:"MED-30291",medicalCardIssueDate:mockDate(-300),medicalCardExpiration:mockDate(430),medicalExaminerName:"Dr. J. Morris",nationalRegistryNumber:"NR-661104",twicCardNumber:null,twicCardExpiration:null,driverQualificationFileStatus:"Complete",mvrCheckDate:mockDate(-200),mvrNextReviewDate:mockDate(165),mvrStatus:"Clear",backgroundCheckDate:mockDate(-500),backgroundCheckStatus:"Clear",drugTestDate:mockDate(-170),drugTestResult:"Negative",alcoholTestDate:mockDate(-170),alcoholTestResult:"Negative",clearinghouseStatus:"Clear",clearinghouseLastQueryDate:mockDate(-160),clearinghouseNextQueryDate:mockDate(205),complianceStatus:"Compliant",accidentHistory:"None reported",violationHistory:"None reported",assignedCarrierId:"mock-carrier-coastal",assignedTruckId:"Truck 4",assignedTrailerId:"Trailer 3",lastLoad:"LD-24084",totalLoads:201,lastAssignmentDate:mockDate(-15),notes:"Inactive while equipment is in maintenance.",tags:["Owner operator"],createdAt:mockDateTime(-700,10),updatedAt:mockDateTime(-8,13)}
  ];

  const invoices = [
    {id:"mock-invoice-1038",invoiceNumber:"INV-1038",carrierId:"mock-carrier-blue-ridge",carrierName:"Blue Ridge Auto Transport",issueDate:mockDate(-5),dueDate:mockDate(2),total:2150,amountPaid:1250,balance:900,status:"Partial",notes:"ACH partial payment received; remaining balance pending.",payments:[{id:"mock-payment-1038-a",paymentDate:mockDate(-1),amount:1250,paymentMethod:"ACH",reference:"ACH-884120",notes:"Partial payment"}],loadIds:["mock-load-004","mock-load-005"],createdAt:mockDateTime(-5,12),updatedAt:mockDateTime(-1,16)},
    {id:"mock-invoice-1037",invoiceNumber:"INV-1037",carrierId:"mock-carrier-piedmont",carrierName:"Piedmont Vehicle Transport",issueDate:mockDate(-11),dueDate:mockDate(-1),total:2030,amountPaid:2030,balance:0,status:"Paid",notes:"Paid in full via ACH.",payments:[{id:"mock-payment-1037-a",paymentDate:mockDate(-3),amount:2030,paymentMethod:"ACH",reference:"ACH-771402",notes:null}],loadIds:["mock-load-007","mock-load-008"],createdAt:mockDateTime(-11,10),updatedAt:mockDateTime(-3,10)},
    {id:"mock-invoice-1039",invoiceNumber:"INV-1039",carrierId:"mock-carrier-piedmont",carrierName:"Piedmont Vehicle Transport",issueDate:mockDate(-2),dueDate:mockDate(8),total:980,amountPaid:0,balance:980,status:"Open",notes:"Commission invoice for completed Raleigh delivery.",payments:[],loadIds:["mock-load-004"],createdAt:mockDateTime(-2,16),updatedAt:null}
  ];

  const transactions = [
    {id:"mock-transaction-001",transactionId:"TXN-260901",date:mockDate(-3),dueDate:null,type:"Income",category:"Commission Revenue",description:"Payment received for INV-1037",carrierId:"mock-carrier-piedmont",carrierName:"Piedmont Vehicle Transport",invoiceId:"mock-invoice-1037",invoiceNumber:"INV-1037",paymentMethod:"ACH",amount:2030,status:"Completed",referenceNumber:"ACH-771402",notes:null,createdAt:mockDateTime(-3,10)},
    {id:"mock-transaction-002",transactionId:"TXN-260902",date:mockDate(-1),dueDate:null,type:"Income",category:"Commission Revenue",description:"Partial payment for INV-1038",carrierId:"mock-carrier-blue-ridge",carrierName:"Blue Ridge Auto Transport",invoiceId:"mock-invoice-1038",invoiceNumber:"INV-1038",paymentMethod:"ACH",amount:1250,status:"Completed",referenceNumber:"ACH-884120",notes:"Partial payment",createdAt:mockDateTime(-1,16)},
    {id:"mock-transaction-003",transactionId:"TXN-260903",date:mockDate(-4),dueDate:null,type:"Expense",category:"Software",description:"Dispatch communications platform",carrierId:null,carrierName:null,invoiceId:null,invoiceNumber:null,paymentMethod:"Card",amount:189,status:"Completed",referenceNumber:"SW-9031",notes:null,createdAt:mockDateTime(-4,9)},
    {id:"mock-transaction-004",transactionId:"TXN-260904",date:mockDate(-2),dueDate:null,type:"Expense",category:"Marketing",description:"Paid media spend — carrier growth campaign",carrierId:null,carrierName:null,invoiceId:null,invoiceNumber:null,paymentMethod:"Card",amount:650,status:"Completed",referenceNumber:"META-4820",notes:null,createdAt:mockDateTime(-2,18)},
    {id:"mock-transaction-005",transactionId:"TXN-260905",date:mockDate(1),dueDate:mockDate(1),type:"Expense",category:"Insurance",description:"General liability monthly premium",carrierId:null,carrierName:null,invoiceId:null,invoiceNumber:null,paymentMethod:"ACH",amount:420,status:"Pending",referenceNumber:null,notes:null,createdAt:mockDateTime(0,8)},
    {id:"mock-transaction-006",transactionId:"TXN-260906",date:mockDate(-6),dueDate:null,type:"Expense",category:"Office",description:"Operational supplies",carrierId:null,carrierName:null,invoiceId:null,invoiceNumber:null,paymentMethod:"Card",amount:126.45,status:"Completed",referenceNumber:"CARD-4018",notes:null,createdAt:mockDateTime(-6,15)},
    {id:"mock-transaction-007",transactionId:"TXN-260907",date:mockDate(3),dueDate:mockDate(3),type:"Income",category:"Commission Revenue",description:"Expected balance for INV-1038",carrierId:"mock-carrier-blue-ridge",carrierName:"Blue Ridge Auto Transport",invoiceId:"mock-invoice-1038",invoiceNumber:"INV-1038",paymentMethod:"ACH",amount:900,status:"Pending",referenceNumber:null,notes:null,createdAt:mockDateTime(0,9)}
  ];

  const documents = [
    {id:"mock-document-001",name:"Signed BOL — LD-24088.pdf",category:"BOL",entityType:"Load",entityId:"mock-load-004",objectPath:"mock/documents/ld-24088-bol.pdf",contentType:"application/pdf",size:482120,notes:"Signed delivery BOL.",uploadedById:"frontend-preview",uploadedByEmail:"preview@landerdispatch.local",createdAt:mockDateTime(-2,16),updatedAt:null,downloadUrl:"data:text/plain;charset=utf-8,Signed%20BOL%20mock%20document"},
    {id:"mock-document-002",name:"COI — Blue Ridge Auto Transport.pdf",category:"Insurance",entityType:"Carrier",entityId:"mock-carrier-blue-ridge",objectPath:"mock/documents/blue-ridge-coi.pdf",contentType:"application/pdf",size:358210,notes:"Current insurance certificate.",uploadedById:"frontend-preview",uploadedByEmail:"preview@landerdispatch.local",createdAt:mockDateTime(-30,10),updatedAt:null,downloadUrl:"data:text/plain;charset=utf-8,Carrier%20COI%20mock%20document"},
    {id:"mock-document-003",name:"W-9 — Piedmont Vehicle Transport.pdf",category:"Tax",entityType:"Carrier",entityId:"mock-carrier-piedmont",objectPath:"mock/documents/piedmont-w9.pdf",contentType:"application/pdf",size:218403,notes:"Carrier W-9.",uploadedById:"frontend-preview",uploadedByEmail:"preview@landerdispatch.local",createdAt:mockDateTime(-80,11),updatedAt:null,downloadUrl:"data:text/plain;charset=utf-8,W9%20mock%20document"},
    {id:"mock-document-004",name:"Rate Confirmation — LD-24091.pdf",category:"Rate Confirmation",entityType:"Load",entityId:"mock-load-001",objectPath:"mock/documents/ld-24091-ratecon.pdf",contentType:"application/pdf",size:311882,notes:"Broker rate confirmation.",uploadedById:"frontend-preview",uploadedByEmail:"preview@landerdispatch.local",createdAt:mockDateTime(-2,11),updatedAt:null,downloadUrl:"data:text/plain;charset=utf-8,Rate%20confirmation%20mock%20document"},
    {id:"mock-document-005",name:"Carrier Packet — Coastal Carriers LLC.pdf",category:"Carrier Packet",entityType:"Carrier",entityId:"mock-carrier-coastal",objectPath:"mock/documents/coastal-packet.pdf",contentType:"application/pdf",size:1148210,notes:"Onboarding packet and authority records.",uploadedById:"frontend-preview",uploadedByEmail:"preview@landerdispatch.local",createdAt:mockDateTime(-120,9),updatedAt:null,downloadUrl:"data:text/plain;charset=utf-8,Carrier%20packet%20mock%20document"},
    {id:"mock-document-006",name:"Broker Agreement — Apex Auto Logistics.pdf",category:"Agreement",entityType:"Broker",entityId:"mock-broker-apex",objectPath:"mock/documents/apex-agreement.pdf",contentType:"application/pdf",size:620940,notes:"Executed service agreement.",uploadedById:"frontend-preview",uploadedByEmail:"preview@landerdispatch.local",createdAt:mockDateTime(-200,13),updatedAt:null,downloadUrl:"data:text/plain;charset=utf-8,Broker%20agreement%20mock%20document"}
  ];

  const auditLogs = [
    {id:"mock-audit-001",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"UPDATE",entityType:"load",entityId:"mock-load-001",summary:"Load LD-24091 moved to Dispatched.",metadata:{status:"Dispatched"},createdAt:mockDateTime(0,8,42)},
    {id:"mock-audit-002",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"CREATE",entityType:"document",entityId:"mock-document-001",summary:"Signed BOL uploaded for LD-24088.",metadata:{category:"BOL"},createdAt:mockDateTime(-2,16,12)},
    {id:"mock-audit-003",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"UPDATE",entityType:"invoice",entityId:"mock-invoice-1038",summary:"Partial payment applied to INV-1038.",metadata:{amount:1250},createdAt:mockDateTime(-1,16,5)},
    {id:"mock-audit-004",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"UPDATE",entityType:"carrier",entityId:"mock-carrier-piedmont",summary:"Carrier compliance marked for review.",metadata:{reason:"Insurance expiration approaching"},createdAt:mockDateTime(-1,15,22)},
    {id:"mock-audit-005",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"CREATE",entityType:"lead",entityId:"mock-lead-manufacturer",summary:"New manufacturer lead created.",metadata:{source:"Trade Show"},createdAt:mockDateTime(-6,14,10)},
    {id:"mock-audit-006",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"UPDATE",entityType:"broker",entityId:"mock-broker-apex",summary:"Broker payment terms confirmed.",metadata:{paymentTerms:"Net 30"},createdAt:mockDateTime(-7,10,30)},
    {id:"mock-audit-007",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"UPDATE",entityType:"company_profile",entityId:"mock-company-profile",summary:"Company profile information updated.",metadata:null,createdAt:mockDateTime(-9,9,45)},
    {id:"mock-audit-008",actorId:"frontend-preview",actorEmail:"preview@landerdispatch.local",action:"CREATE",entityType:"transaction",entityId:"mock-transaction-002",summary:"Income transaction recorded for INV-1038.",metadata:{amount:1250},createdAt:mockDateTime(-1,16,7)}
  ];

  const companyProfile = {
    id:"mock-company-profile",companyName:"Lander Dispatch",legalCompanyName:"Lander Solutions Tech LLC",dbaName:"Lander Dispatch",einNumber:"88-0002409",mcNumber:"MC-240901",usdotNumber:"3982409",companyPhone:"(704) 555-0100",companyEmail:"operations@landerdispatch.example",website:"https://landerdispatch.example",streetAddress:"4100 Operations Blvd",city:"Charlotte",state:"NC",zipCode:"28208",country:"United States",businessHours:"Mon-Fri 7:00-19:00 ET",logoUrl:null
  };

  return { carriers, brokers, loads, contacts, leads, drivers, invoices, transactions, documents, auditLogs, companyProfile };
}
