import { mockDate, mockDateTime } from "./date";

export function createMockMarketingState() {
  const briefingLaunch = "mock-briefing-launch";
  const briefingRemarketing = "mock-briefing-remarketing";
  const campaignAwareness = "mock-campaign-awareness";
  const campaignRetargeting = "mock-campaign-retargeting";
  const contentCarousel = "mock-content-carousel";
  const contentReel = "mock-content-reel";
  const contentEmail = "mock-content-email";
  const contentCaseStudy = "mock-content-case-study";

  return {
    briefings: [
      {
        id: briefingLaunch,
        title: "Lander Dispatch — Carrier Growth Campaign",
        type: "Campaign",
        status: "Approved",
        deadline: mockDate(7),
        owners: ["Marketing", "Operations"],
        objective: "Generate qualified carrier relationships in the Southeast and reinforce operational credibility.",
        context: "Increase available capacity while positioning Lander Dispatch as a reliable operations partner.",
        audience: "Owner-operators and small vehicle transport carriers with active authority.",
        positioning: "Professional dispatch operations with clear communication and reliable load coordination.",
        tone: "Direct, professional and operationally credible.",
        requirements: "Use real operational benefits, avoid exaggerated earnings claims and keep calls to action specific.",
        creativeDirection: "Clean transportation visuals, dispatch screens and real workflow language.",
        references: "Operational dashboards, carrier onboarding and load lifecycle.",
        visualGuidelines: "Navy, white and restrained blue accents with high-contrast typography.",
        textGuidelines: "Short proof-driven copy focused on reduced friction, visibility and consistent communication.",
        market: "Southeast vehicle transport market.",
        competitors: "Independent dispatch services and small broker operations.",
        trends: "Carrier demand for faster communication, payment visibility and digital onboarding.",
        channels: ["Instagram", "Facebook", "LinkedIn"],
        restrictions: "No guaranteed revenue or guaranteed load-volume claims.",
        resources: "Brand kit, dispatch product screenshots and carrier onboarding flow.",
        expectations: "Drive qualified conversations and measurable profile visits.",
        deliverables: ["Campaign concept", "Carousel", "Short video", "Lead form copy"],
        timeline: "Two-week launch sprint followed by optimization.",
        executionPlan: "Launch awareness creative, validate engagement, then retarget qualified visitors.",
        aiRecommendations: "Lead with operational pain points and proof of workflow clarity rather than generic logistics messaging.",
      },
      {
        id: briefingRemarketing,
        title: "Broker Retargeting — Faster Load Coordination",
        type: "Content",
        status: "In Review",
        deadline: mockDate(10),
        owners: ["Marketing", "CRM"],
        objective: "Re-engage broker prospects who viewed services but did not start a conversation.",
        context: "Use social proof and response-time messaging to reduce hesitation.",
        audience: "Vehicle transport brokers and dealer logistics coordinators.",
        positioning: "Responsive dispatch support that protects broker-customer relationships.",
        tone: "Confident and concise.",
        requirements: "Include measurable workflow benefits and one CTA.",
        creativeDirection: "Before/after operational workflow with clear status visibility.",
        references: "CRM pipeline and dispatch status examples.",
        visualGuidelines: "Product-led layouts with minimal decorative imagery.",
        textGuidelines: "Specific, low-hype claims.",
        market: "U.S. vehicle logistics.",
        competitors: "Generalist dispatch teams.",
        trends: "Increased expectation for real-time status updates.",
        channels: ["Facebook", "Google Ads", "Email"],
        restrictions: "No unsupported performance statistics.",
        resources: "CRM screenshots and customer workflow examples.",
        expectations: "Increase qualified return visits and booked discovery calls.",
        deliverables: ["Retargeting ads", "Email sequence", "Landing page section"],
        timeline: "Three-week retargeting cycle.",
        executionPlan: "Segment audiences by prior interaction and tailor CTA by funnel stage.",
        aiRecommendations: "Use separate creative for brokers versus dealers to avoid generic messaging.",
      },
    ],
    campaigns: [
      {
        id: campaignAwareness,
        name: "Carrier Growth — Southeast",
        targetType: "Carrier",
        targetName: "Southeast owner-operators",
        type: "Awareness",
        status: "Active",
        owner: "Maya Collins",
        budget: 3500,
        startDate: mockDate(-6),
        endDate: mockDate(24),
        objective: "Generate qualified carrier conversations and increase onboarding starts.",
        audience: "Active vehicle transport carriers operating NC, SC, GA, VA and TN.",
        segmentation: "Owner-operators, 1–5 truck fleets, active authority, vehicle transport interest.",
        platforms: ["Instagram", "Facebook", "LinkedIn"],
        notes: "Creative should emphasize operational clarity and payment visibility.",
        metrics: { reach: 48200, impressions: 73900, engagement: 3860, clicks: 2140, conversions: 126, roi: 42, costPerResult: 27.78 },
      },
      {
        id: campaignRetargeting,
        name: "Broker Retargeting — Q3",
        targetType: "Broker",
        targetName: "Warm broker prospects",
        type: "Remarketing",
        status: "Planned",
        owner: "Maya Collins",
        budget: 1800,
        startDate: mockDate(5),
        endDate: mockDate(26),
        objective: "Convert warm broker interest into discovery calls.",
        audience: "Visitors who engaged with service pages or CRM outreach.",
        segmentation: "30-day site visitors and engaged social audiences.",
        platforms: ["Facebook", "Google Ads", "Email"],
        notes: "Coordinate message sequencing with CRM follow-up.",
        metrics: { reach: 0, impressions: 0, engagement: 0, clicks: 0, conversions: 0, roi: 0, costPerResult: 0 },
      },
    ],
    contents: [
      {
        id: contentCarousel,
        title: "5 signs your carrier dispatch workflow is costing time",
        targetType: "Carrier",
        targetName: "Southeast owner-operators",
        type: "Carousel",
        channel: "Instagram",
        channels: ["Instagram", "Facebook"],
        status: "Scheduled",
        approval: "Approved",
        publishDate: mockDate(1),
        publishTime: "10:30",
        owner: "Maya Collins",
        copy: "A strong dispatch workflow should reduce uncertainty, not create more of it. Here are five signals that your operation needs a cleaner process.",
        notes: "Use product-led slides and final CTA to start a carrier conversation.",
        campaignId: campaignAwareness,
        hashtags: "#carhauling #autotransport #dispatch",
        location: "Southeast US",
        integratedAccountId: "meta-primary",
        mediaName: "carrier-workflow-carousel-v3",
        mediaUrl: "https://example.com/mock/carrier-workflow-carousel",
      },
      {
        id: contentReel,
        title: "60-second load lifecycle walkthrough",
        targetType: "Carrier",
        targetName: "Owner-operators",
        type: "Reel / Short Video",
        channel: "Instagram",
        channels: ["Instagram", "TikTok", "YouTube"],
        status: "In Review",
        approval: "Pending",
        publishDate: mockDate(3),
        publishTime: "13:00",
        owner: "Jordan Blake",
        copy: "From load assignment to signed delivery: one clear workflow, fewer status gaps.",
        notes: "Waiting for final captions and compliance review.",
        campaignId: campaignAwareness,
        hashtags: "#vehicletransport #dispatchsoftware",
        location: "",
        integratedAccountId: "meta-primary",
        mediaName: "load-lifecycle-reel-v2",
        mediaUrl: "https://example.com/mock/load-lifecycle-reel",
      },
      {
        id: contentEmail,
        title: "Broker follow-up — faster status visibility",
        targetType: "Broker",
        targetName: "Warm broker prospects",
        type: "Email",
        channel: "Email",
        channels: ["Email"],
        status: "Draft",
        approval: "Pending",
        publishDate: mockDate(6),
        publishTime: "09:00",
        owner: "Maya Collins",
        copy: "When customers ask where a vehicle is, the answer should already be available. Lander Dispatch keeps the operational handoff visible from pickup through delivery.",
        notes: "Needs CRM segment review before scheduling.",
        campaignId: campaignRetargeting,
        hashtags: "",
        location: "",
        integratedAccountId: "resend-primary",
        mediaName: "",
        mediaUrl: "",
      },
      {
        id: contentCaseStudy,
        title: "Case study: reducing status-chasing across active loads",
        targetType: "Company",
        targetName: "Lander Dispatch",
        type: "Article",
        channel: "Website",
        channels: ["Website", "LinkedIn"],
        status: "Published",
        approval: "Approved",
        publishDate: mockDate(-4),
        publishTime: "11:00",
        owner: "Jordan Blake",
        copy: "A practical breakdown of how a structured dispatch workflow reduces repeated status requests and improves handoffs.",
        notes: "Use in broker retargeting as proof asset.",
        campaignId: campaignRetargeting,
        hashtags: "",
        location: "",
        integratedAccountId: "",
        mediaName: "status-visibility-case-study",
        mediaUrl: "https://example.com/mock/status-visibility-case-study",
      },
    ],
    tasks: [
      {
        id: "mock-marketing-task-001",
        title: "Finalize carrier workflow carousel",
        workstream: "Creative",
        status: "In Progress",
        priority: "High",
        owner: "Jordan Blake",
        reviewer: "Maya Collins",
        deadline: mockDate(0),
        description: "Finalize slide hierarchy, verify CTA and prepare export variants for Instagram and Facebook.",
        deliverable: "Approved 1080×1350 carousel + Facebook adaptation",
        campaignId: campaignAwareness,
        briefingId: briefingLaunch,
        contentId: contentCarousel,
        channels: ["Instagram", "Facebook"],
        approval: "Pending",
        referenceUrl: "https://example.com/mock/carrier-workflow-carousel",
        checklist: [
          { id: "mock-marketing-task-001-a", label: "Review final copy", done: true },
          { id: "mock-marketing-task-001-b", label: "Export platform variants", done: false },
          { id: "mock-marketing-task-001-c", label: "Submit for approval", done: false },
        ],
      },
      {
        id: "mock-marketing-task-002",
        title: "Review captions for load lifecycle reel",
        workstream: "Content",
        status: "In Review",
        priority: "High",
        owner: "Jordan Blake",
        reviewer: "Olivia Grant",
        deadline: mockDate(1),
        description: "Verify captions, compliance wording and CTA before final scheduling.",
        deliverable: "Final captioned vertical video",
        campaignId: campaignAwareness,
        briefingId: briefingLaunch,
        contentId: contentReel,
        channels: ["Instagram", "TikTok", "YouTube"],
        approval: "Pending",
        referenceUrl: "https://example.com/mock/load-lifecycle-reel",
        checklist: [
          { id: "mock-marketing-task-002-a", label: "Caption proofread", done: true },
          { id: "mock-marketing-task-002-b", label: "Compliance review", done: false },
        ],
      },
      {
        id: "mock-marketing-task-003",
        title: "Build broker remarketing audience",
        workstream: "Paid Media",
        status: "Planned",
        priority: "Medium",
        owner: "Maya Collins",
        reviewer: "",
        deadline: mockDate(4),
        description: "Prepare 30-day engaged audience and exclude current active customers.",
        deliverable: "Validated Meta + Google remarketing audiences",
        campaignId: campaignRetargeting,
        briefingId: briefingRemarketing,
        contentId: "",
        channels: ["Facebook", "Google Ads"],
        approval: "Not Required",
        referenceUrl: "",
        checklist: [
          { id: "mock-marketing-task-003-a", label: "Define inclusion criteria", done: true },
          { id: "mock-marketing-task-003-b", label: "Define exclusions", done: false },
          { id: "mock-marketing-task-003-c", label: "Validate estimated audience size", done: false },
        ],
      },
      {
        id: "mock-marketing-task-004",
        title: "Segment CRM list for broker email sequence",
        workstream: "Email",
        status: "Blocked",
        priority: "Urgent",
        owner: "Maya Collins",
        reviewer: "Daniel Carter",
        deadline: mockDate(2),
        description: "Waiting on CRM owner validation before excluding current partners and inactive contacts.",
        deliverable: "Clean broker remarketing email segment",
        campaignId: campaignRetargeting,
        briefingId: briefingRemarketing,
        contentId: contentEmail,
        channels: ["Email"],
        approval: "Changes Requested",
        referenceUrl: "",
        checklist: [
          { id: "mock-marketing-task-004-a", label: "Export warm broker prospects", done: true },
          { id: "mock-marketing-task-004-b", label: "Validate exclusions with CRM", done: false },
        ],
      },
      {
        id: "mock-marketing-task-005",
        title: "Repurpose case study for LinkedIn",
        workstream: "Social Media",
        status: "Backlog",
        priority: "Low",
        owner: "Jordan Blake",
        reviewer: "",
        deadline: mockDate(8),
        description: "Convert published case study into a concise LinkedIn document post.",
        deliverable: "LinkedIn document post",
        campaignId: campaignRetargeting,
        briefingId: briefingRemarketing,
        contentId: contentCaseStudy,
        channels: ["LinkedIn"],
        approval: "Not Required",
        referenceUrl: "https://example.com/mock/status-visibility-case-study",
        checklist: [],
      },
      {
        id: "mock-marketing-task-006",
        title: "UTM naming audit for active campaign",
        workstream: "Analytics",
        status: "Completed",
        priority: "Medium",
        owner: "Maya Collins",
        reviewer: "",
        deadline: mockDate(-2),
        description: "Standardize source, medium and campaign naming across current campaign links.",
        deliverable: "Validated UTM map",
        campaignId: campaignAwareness,
        briefingId: briefingLaunch,
        contentId: "",
        channels: ["Instagram", "Facebook", "LinkedIn"],
        approval: "Approved",
        referenceUrl: "",
        checklist: [
          { id: "mock-marketing-task-006-a", label: "Audit existing links", done: true },
          { id: "mock-marketing-task-006-b", label: "Correct inconsistent UTMs", done: true },
        ],
      },
    ],
    aiHistory: [
      {
        id: "mock-ai-history-001",
        kind: "Ideas",
        prompt: "Create three content angles for carrier onboarding",
        output: "1. Reduce status-chasing.\n2. Make every handoff visible.\n3. Turn onboarding into a repeatable checklist.",
        createdAt: mockDateTime(-2, 14, 20),
      },
      {
        id: "mock-ai-history-002",
        kind: "Planning",
        prompt: "Plan a two-week launch sequence for the carrier growth campaign",
        output: "Week 1: awareness carousel, workflow reel and founder-style post.\nWeek 2: proof asset, retargeting creative and direct-response CTA.",
        createdAt: mockDateTime(-1, 10, 5),
      },
    ],
  };
}
