import { mockDate } from "./date";

export function createMockOperationalTasks() {
  return [
    {
      id: "mock-task-001",
      title: "Confirm pickup release for LD-24091",
      context: "Load",
      targetName: "LD-24091 · 2023 BMW X5",
      sector: "Dispatch",
      type: "Operational",
      status: "In Progress",
      priority: "Urgent",
      owner: "Marcus Reed",
      deadline: mockDate(0),
      description: "Verify auction release, driver arrival and gate pass before pickup.",
      checklist: [
        { id: "mock-task-001-a", label: "Confirm release with auction", done: true },
        { id: "mock-task-001-b", label: "Send gate pass to driver", done: true },
        { id: "mock-task-001-c", label: "Receive pickup condition photos", done: false },
      ],
    },
    {
      id: "mock-task-002",
      title: "Collect updated insurance certificate",
      context: "Carrier",
      targetName: "Piedmont Vehicle Transport",
      sector: "Compliance",
      type: "Compliance",
      status: "To Do",
      priority: "High",
      owner: "Olivia Grant",
      deadline: mockDate(2),
      description: "Current certificate is approaching expiration. Request updated COI before assigning new loads.",
      checklist: [
        { id: "mock-task-002-a", label: "Email carrier compliance contact", done: true },
        { id: "mock-task-002-b", label: "Validate policy limits", done: false },
        { id: "mock-task-002-c", label: "Attach approved certificate", done: false },
      ],
    },
    {
      id: "mock-task-003",
      title: "Reconcile partial payment on INV-1038",
      context: "Broker",
      targetName: "Apex Auto Logistics",
      sector: "Accounting",
      type: "Financial",
      status: "Review",
      priority: "High",
      owner: "Sophia Bennett",
      deadline: mockDate(1),
      description: "Match ACH receipt to invoice and verify remaining open balance.",
      checklist: [
        { id: "mock-task-003-a", label: "Locate ACH transaction", done: true },
        { id: "mock-task-003-b", label: "Apply partial payment", done: true },
        { id: "mock-task-003-c", label: "Confirm remaining balance", done: false },
      ],
    },
    {
      id: "mock-task-004",
      title: "Follow up on fleet transport proposal",
      context: "Contact",
      targetName: "Northstar Auto Group",
      sector: "CRM",
      type: "Follow-up",
      status: "Backlog",
      priority: "Medium",
      owner: "Daniel Carter",
      deadline: mockDate(4),
      description: "Contact customer after proposal review and qualify expected weekly volume.",
      checklist: [],
    },
    {
      id: "mock-task-005",
      title: "Archive signed BOL for LD-24084",
      context: "Load",
      targetName: "LD-24084 · 2022 Ford F-150",
      sector: "Operations",
      type: "Documentation",
      status: "Completed",
      priority: "Low",
      owner: "Marcus Reed",
      deadline: mockDate(-2),
      description: "Validate signature and archive the final BOL in load documents.",
      checklist: [
        { id: "mock-task-005-a", label: "Validate delivery signature", done: true },
        { id: "mock-task-005-b", label: "Upload final BOL", done: true },
      ],
    },
    {
      id: "mock-task-006",
      title: "Prepare weekly exception summary",
      context: "Company",
      targetName: "Lander Dispatch",
      sector: "Administration",
      type: "Operational",
      status: "To Do",
      priority: "Medium",
      owner: "Olivia Grant",
      deadline: mockDate(5),
      description: "Summarize delayed loads, compliance exceptions and overdue receivables for the weekly review.",
      checklist: [],
    },
  ];
}
