import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, Eye, Facebook, Globe2, Instagram, Mail, MousePointerClick, PlaySquare, Target, TrendingUp } from "lucide-react";
import { MarketingSectionCard } from "../components/MarketingPrimitives";
import { useMarketingState } from "../state";

type PlatformId = "overview" | "Instagram" | "Facebook" | "TikTok" | "YouTube" | "Google Ads" | "Email" | "Website";
const PLATFORMS: Array<{ id: PlatformId; label: string; icon: typeof BarChart3 }> = [
  { id:"overview",label:"Overview",icon:BarChart3 }, { id:"Instagram",label:"Instagram",icon:Instagram }, { id:"Facebook",label:"Facebook",icon:Facebook },
  { id:"TikTok",label:"TikTok",icon:PlaySquare }, { id:"YouTube",label:"YouTube",icon:PlaySquare }, { id:"Google Ads",label:"Google Ads",icon:Target },
  { id:"Email",label:"Email",icon:Mail }, { id:"Website",label:"Website",icon:Globe2 },
];
function compact(value:number){return new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(value)}
function money(value:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value)}

export default function MarketingMetricsPage(){
  const[state]=useMarketingState(); const[platform,setPlatform]=useState<PlatformId>("overview");
  const scoped=useMemo(()=>platform==="overview"?state.campaigns:state.campaigns.filter(c=>c.platforms.includes(platform)),[state.campaigns,platform]);
  const aggregate=useMemo(()=>scoped.reduce((a,c)=>({reach:a.reach+c.metrics.reach,impressions:a.impressions+c.metrics.impressions,engagement:a.engagement+c.metrics.engagement,clicks:a.clicks+c.metrics.clicks,conversions:a.conversions+c.metrics.conversions,budget:a.budget+c.budget,roi:a.roi+c.metrics.roi,cost:a.cost+c.metrics.costPerResult}),{reach:0,impressions:0,engagement:0,clicks:0,conversions:0,budget:0,roi:0,cost:0}),[scoped]);
  const ctr=aggregate.impressions?aggregate.clicks/aggregate.impressions*100:0; const cvr=aggregate.clicks?aggregate.conversions/aggregate.clicks*100:0; const avgRoi=scoped.length?aggregate.roi/scoped.length:0; const avgCost=scoped.length?aggregate.cost/scoped.length:0;
  const kpis=[{label:"Reach",value:compact(aggregate.reach)},{label:"Impressions",value:compact(aggregate.impressions)},{label:"Clicks",value:compact(aggregate.clicks)},{label:"Conversions",value:compact(aggregate.conversions)},{label:"CTR",value:`${ctr.toFixed(2)}%`},{label:"ROI",value:`${avgRoi.toFixed(1)}%`}];
  const trend=useMemo(()=>{const ratios=[.48,.57,.65,.74,.86,1];return ratios.map((ratio,index)=>({label:["P1","P2","P3","P4","P5","P6"][index],value:Math.round(aggregate.impressions*ratio)}))},[aggregate.impressions]);
  const summary=[{label:"Campaigns monitored",value:String(scoped.length)},{label:"Media spend",value:money(aggregate.budget)},{label:"Engagement",value:compact(aggregate.engagement)},{label:"Conversion rate",value:`${cvr.toFixed(2)}%`},{label:"Average cost / result",value:money(avgCost)}];
  const ranking=[...scoped].sort((a,b)=>b.metrics.conversions-a.metrics.conversions||b.metrics.reach-a.metrics.reach);
  return <div className="space-y-6 p-4 sm:p-6 lg:p-8">
    <div className="flex gap-1 overflow-x-auto rounded-lg border border-slate-200 bg-white p-1">{PLATFORMS.map(tab=>{const Icon=tab.icon;const active=tab.id===platform;return <button key={tab.id} type="button" onClick={()=>setPlatform(tab.id)} className={`flex h-9 shrink-0 items-center gap-2 rounded-md px-3 text-xs font-medium transition-colors ${active?"bg-[#1E3D7A] text-white":"text-slate-500 hover:bg-slate-50 hover:text-[#0B1E36]"}`}><Icon className="h-3.5 w-3.5"/>{tab.label}</button>})}</div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{kpis.map(item=><div key={item.label} className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-[11px] font-medium tracking-wide text-slate-500">{item.label}</p><p className="mt-2 text-2xl font-bold tabular-nums text-[#0B1E36]">{item.value}</p></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
      <MarketingSectionCard title={platform==="overview"?"Consolidated Evolution":`${platform} · Evolution`} description={platform==="overview"?"Aggregate performance across monitored marketing platforms":"Simulated series for the selected platform"}><div className="h-[340px] w-full">{aggregate.impressions>0?<ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:12,right:16,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={(v)=>compact(Number(v))} width={54}/><Tooltip formatter={(value)=>[compact(Number(value)),"Impressions"]}/><Area type="monotone" dataKey="value" stroke="currentColor" strokeWidth={2} fill="currentColor" fillOpacity={0.12} className="text-[#1E3D7A]"/></AreaChart></ResponsiveContainer>:<Empty message="Not enough data to display evolution for this platform."/>}</div></MarketingSectionCard>
      <MarketingSectionCard title={platform==="overview"?"Consolidated Summary":`Summary · ${platform}`} description="Quick reading of the main indicators"><div className="space-y-2">{summary.map(item=><div key={item.label} className="flex items-start justify-between gap-3 rounded-md bg-slate-50 px-3 py-2"><span className="text-xs text-slate-500">{item.label}</span><span className="max-w-[180px] text-right text-xs font-semibold">{item.value}</span></div>)}</div></MarketingSectionCard>
    </div>
    <MarketingSectionCard title={platform==="overview"?"Top Campaigns":`Ranking · ${platform}`} description="Performance ranking by campaign and platform">{ranking.length?<div className="space-y-2"><div className="hidden grid-cols-[60px_1.4fr_1fr_120px_130px] gap-3 px-3 text-[11px] font-semibold tracking-wide text-slate-500 lg:grid"><span>Position</span><span>Campaign</span><span>Platforms</span><span>Result</span><span>Status</span></div>{ranking.map((item,index)=><div key={item.id} className="grid gap-3 rounded-lg border border-slate-200 bg-white p-3 lg:grid-cols-[60px_1.4fr_1fr_120px_130px] lg:items-center"><div><span className="flex h-8 w-8 items-center justify-center rounded-md bg-blue-50 text-sm font-bold text-[#1E3D7A]">{index+1}</span></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.name}</p><p className="text-[11px] text-slate-500">{item.type}</p></div><p className="truncate text-xs text-slate-500">{item.platforms.join(", ")||"—"}</p><div><p className="text-sm font-semibold tabular-nums">{item.metrics.conversions.toLocaleString()}</p><p className="text-[11px] text-slate-500">Conversions</p></div><span className="inline-flex w-fit rounded-full border border-slate-200 bg-slate-50 px-2 py-1 text-[10px] font-semibold">{item.status}</span></div>)}</div>:<Empty message="No campaigns found for this platform."/>}</MarketingSectionCard>
  </div>;
}
function Empty({message}:{message:string}){return <div className="flex min-h-40 flex-col items-center justify-center text-center text-sm text-slate-500"><TrendingUp className="mb-3 h-7 w-7 text-slate-300"/><p>{message}</p></div>}
